parameters:
    pierstoval_cors.cors_listener.class: Pierstoval\Bundle\CorsBundle\EventListener\CorsListener
    pierstoval_cors.options_resolver.class: Pierstoval\Bundle\CorsBundle\Options\Resolver
    pierstoval_cors.options_provider.config.class: Pierstoval\Bundle\CorsBundle\Options\ConfigProvider

services:
    pierstoval_cors.cors_listener:
        class: %pierstoval_cors.cors_listener.class%
        arguments:
            - @event_dispatcher
            - @pierstoval_cors.options_resolver
        tags:
            - { name: kernel.event_listener, event: "kernel.request", method: "onKernelRequest", priority: "10000" }

    pierstoval_cors.options_resolver:
        class: %pierstoval_cors.options_resolver.class%
        public: false

    pierstoval_cors.options_provider.config:
        class: %pierstoval_cors.options_provider.config.class%
        arguments:
            - %pierstoval_cors.map%
            - %pierstoval_cors.defaults%
        tags:
            - { name: "pierstoval_cors.options_provider", priority: "-1" }
