easy_admin:
    site_name: Esteren

    list:
        max_results: 50

    design:
        brand_color: 'rgb(88, 88, 216)'

        assets:
            css:
                - 'css/initializer.css'
                - 'css/admin.css'

        form_theme:
            - 'form/easyadmin_form_theme.html.twig'

        menu:
            - { label: 'admin.links.back_to_site', route: 'agate_portal_home' }

            - { label: 'admin.menu.site' }
            - { entity: 'PortalElement', icon: 'file-text' }

            - { label: 'admin.menu.users' }
            - { entity: 'Users', icon: 'users' }
            - { entity: 'Subscriptions', icon: 'address-card' }

            - { label: 'admin.menu.esterenmaps' }
            - { entity: 'Maps', icon: 'map' }
            - { entity: 'Factions', icon: 'flag' }

            -   label: 'admin.menu.esterenmaps_data'
                children:
                    - { entity: 'Markers' }
                    - { entity: 'Routes' }
                    - { entity: 'Zones' }

            -   label: 'admin.menu.types'
                children:
                    - { entity: 'MarkersTypes' }
                    - { entity: 'RoutesTypes' }
                    - { entity: 'ZonesTypes' }
                    - { entity: 'TransportTypes' }
