easy_admin:
    entities:
        Subscriptions:
            class: Subscription\Entity\Subscription

            controller: Subscription\Controller\Admin\AdminSubscriptionController

            disabled_actions:
                - edit
                - delete

            list:
                fields:
                    - id
                    - user
                    - { property: type, template: easy_admin/field_translatable.html.twig }
                    - { property: startsAt, template: easy_admin/field_date.html.twig }
                    - { property: endsAt, template: easy_admin/field_date.html.twig }

            new:
                fields:
                    - user
                    - property: startsAt
                      type: date
                      type_options:
                          input: datetime_immutable
                          widget: single_text

                    - property: endsAt
                      type: date
                      type_options:
                          input: datetime_immutable
                          widget: single_text

                    - property: type
                      type: choice
                      type_options:
                          choices: !php/const Subscription\SubscriptionType::TYPES
