parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver: pdo_mysql
                url: '%database_url%'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
            legacy:
                driver: pdo_mysql
                url: '%database_url_legacy%'
                charset: utf8
                logging: false
                profiling: false
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            Agate:
                type: annotation
                dir: '%kernel.project_dir%/src/Agate/Entity/'
                is_bundle: false
                prefix: Agate\Entity
                alias: Agate
            CorahnRin:
                type: annotation
                dir: '%kernel.project_dir%/src/CorahnRin/Entity/'
                is_bundle: false
                prefix: CorahnRin\Entity
                alias: CorahnRin
            EsterenMaps:
                type: annotation
                dir: '%kernel.project_dir%/src/EsterenMaps/Entity/'
                is_bundle: false
                prefix: EsterenMaps\Entity
                alias: EsterenMaps
            User:
                type: annotation
                dir: '%kernel.project_dir%/src/User/Entity/'
                is_bundle: false
                prefix: User\Entity
                alias: User
            Subscription:
                type: annotation
                dir: '%kernel.project_dir%/src/Subscription/Entity/'
                is_bundle: false
                prefix: Subscription\Entity
                alias: Subscription
            Voucher:
                type: annotation
                dir: '%kernel.project_dir%/src/Voucher/Entity/'
                is_bundle: false
                prefix: Voucher\Entity
                alias: Voucher
