doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        # Override the default repository to get some more good tools
        filters:
            # Activate SoftDeleteable for some entities
            # There are some other filters down there
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            agate:
                type: annotation
                dir: '%kernel.project_dir%/src/Agate/Entity/'
                is_bundle: false
                prefix: Agate
            corahn_rin:
                type: annotation
                dir: '%kernel.project_dir%/src/CorahnRin/Entity/'
                is_bundle: false
                prefix: CorahnRin
            esteren:
                type: annotation
                dir: '%kernel.project_dir%/src/Esteren/Entity/'
                is_bundle: false
                prefix: Esteren
            esteren_maps:
                type: annotation
                dir: '%kernel.project_dir%/src/EsterenMaps/Entity/'
                is_bundle: false
                prefix: EsterenMaps

    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                url:      '%database_url%'
                charset:  utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            legacy:
                driver:    pdo_mysql
                url:      '%database_url_legacy%'
                charset:   utf8
                logging:   false
                profiling: false
