easy_admin:
    entities:
        PortalElement:
            class: Agate\Entity\PortalElement
            label: PortalElement
            controller: Agate\Controller\Admin\PortalElementController

            list:
                actions:
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: portal, label: 'admin.entities.portalElement.portal' }
                    - { property: locale, label: 'admin.entities.portalElement.locale' }
                    - property: imageUrl
                      template: 'easy_admin/fields/portal_image.html.twig'
                      label: 'admin.entities.portalElement.image'
                    - { property: title, label: 'admin.entities.portalElement.title' }
                    - { property: subtitle, label: 'admin.entities.portalElement.subtitle' }
                    - { property: buttonText, label: 'admin.entities.portalElement.buttonText' }

            new:
                fields:
                    - property: portal
                      label: 'admin.entities.portalElement.portal'
                      type: choice
                      type_options:
                          expanded: true
                          choice_translation_domain: false
                          choices:
                              Agate: agate
                              Esteren: esteren
                              Dragons: dragons

                    - property: locale
                      label: 'admin.entities.portalElement.locale'
                      type: choice
                      type_options:
                          expanded: true
                          choices: '%locales%'
                          choice_translation_domain: Languages

                    - { property: title, label: 'admin.entities.portalElement.title' }
                    - property: subtitle
                      label: 'admin.entities.portalElement.subtitle'
                      type_options: { required: false }
                    - property: buttonLink
                      label: 'admin.entities.portalElement.buttonLink'
                      type_options: { required: false }
                    - property: buttonText
                      label: 'admin.entities.portalElement.buttonText'
                      type_options: { required: false }

                    - property: image
                      type: file
                      virtual: false
                      label: 'admin.entities.portalElement.image'
                      help: 'admin.entities.portalElement.image_help'
                      type_options:
                          required: true

            edit:
                fields:
                    - property: portal
                      label: 'admin.entities.portalElement.portal'
                      type: text
                      type_options:
                          disabled: true
                          attr:
                              readonly: readonly

                    - property: locale
                      label: 'admin.entities.portalElement.locale'
                      type: text
                      type_options:
                          disabled: true
                          attr:
                              readonly: readonly

                    - { property: title, label: 'admin.entities.portalElement.title' }
                    - property: subtitle
                      label: 'admin.entities.portalElement.subtitle'
                      type_options: { required: false }
                    - property: buttonLink
                      label: 'admin.entities.portalElement.buttonLink'
                      type_options: { required: false }
                    - property: buttonText
                      label: 'admin.entities.portalElement.buttonText'
                      type_options: { required: false }

                    - property: image
                      type: file
                      label: 'admin.entities.portalElement.image'
                      help: 'admin.entities.portalElement.image_help'
                      type_options:
                          required: false

        Users:
            class: User\Entity\User

            controller: User\Controller\Admin\AdminUserController

            disabled_actions:
                - edit
                - delete

            list:
                actions:
                    - show

                fields:
                    - id
                    - username
                    - email
                    - roles
                    - { property: emailConfirmed, type: boolean }

            show:
                fields:
                    - id
                    - username
                    - usernameCanonical
                    - email
                    - emailCanonical
                    - roles
                    - emailConfirmed
                    - ululeUsername
                    - createdAt
                    - updatedAt

            new:
                fields:
                    - username
                    - email
                    - property: plainPassword
                      type: text
                      help: admin.entities.users.password_help
                      type_options:
                          help: admin.entities.users.password_help

                    - property: roles
                      type: choice
                      type_options:
                          expanded: true
                          multiple: true
                          choices:
                              admin.entities.users.roles.backer_travels: ROLE_BACKER_TRAVELS

        Subscriptions:
            class: User\Entity\Subscription

            controller: User\Controller\Admin\AdminSubscriptionController

            disabled_actions:
                - edit
                - delete

            list:
                fields:
                    - id
                    - user
                    - { property: type, template: easy_admin/field_translatable.html.twig }
                    - { property: startsAt, template: easy_admin/field_date.html.twig }
                    - { property: endsAt, template: easy_admin/field_date.html.twig }

            new:
                fields:
                    - user
                    - property: startsAt
                      type: date
                      type_options:
                          input: datetime_immutable
                          widget: single_text

                    - property: endsAt
                      type: date
                      type_options:
                          input: datetime_immutable
                          widget: single_text

                    - property: type
                      type: choice
                      type_options:
                          choices: !php/const User\Subscription\SubscriptionType::TYPES
