framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    csrf_protection: true
    http_method_override: true

    assets:
        version: '%version_code%'
        version_format: '%%s?assetv=%%s'
    trusted_hosts:
        - '%env(ESTEREN_DOMAIN)%$'
        - '%env(AGATE_DOMAIN)%$'
        - '%env(DRAGONS_DOMAIN)%$'
        - '%env(VERMINE_DOMAIN)%$'
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:      session.handler.native_file
        save_path:       '%kernel.project_dir%/var/sessions/%kernel.environment%'
        enabled:         true
        name:            AgateSessionCookie
        gc_maxlifetime:  864000
        cookie_httponly: true
        cookie_lifetime: 86400
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
