framework:
    #esi: true
    #fragments: true
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    php_errors:
        log: true
    assets:
        version: '%version_code%'
        version_format: '%%s?assetv=%%s'
    trusted_hosts:
        - '%env(ESTEREN_DOMAIN)%$'
        - '%env(AGATE_DOMAIN)%$'
        - '%env(DRAGONS_DOMAIN)%$'
        - '%env(VERMINE_DOMAIN)%$'
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:      session.handler.native_file
        save_path:       '%kernel.project_dir%/var/sessions/%kernel.environment%'
        enabled:         true
        name:            AgateSessionCookie
        gc_maxlifetime:  864000
        cookie_httponly: true
        cookie_lifetime: 86400
        # To add when SF 4.2 releases
        #cookie_samesite: lax
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        prefix_seed: agate/apps

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
