ivory_ck_editor:
    input_sync: true
    default_config: base_config
    jquery: true
    configs:
        base_config:
            language: '%locale%'
            allowedContent: true
            toolbar:
                - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] }
                - { name: 'links',       items: [ 'Link', 'Unlink', 'Anchor' ] }
                - { name: 'insert',      items: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ] }
                - { name: 'tools',       items: [ 'Maximize' ] }
                - '/'
                - { name: 'paragraph',   items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ] }
                - { name: 'styles',      items: [ 'Styles', 'Format' ] }
                - { name: 'document',    items: [ 'Source', '-' ] }
                - { name: 'about',       items: [ 'About' ] }
