# This allows using the default layout for Pages and Categories
# See: https://github.com/Orbitale/CmsBundle
orbitale_cms:
    page_class:     Esteren\PortalBundle\Entity\Page
    category_class: Esteren\PortalBundle\Entity\Category
    layouts:
        corahnrin:
            resource: 'corahn_rin/layout.html.twig'
            host: '%esteren_domains.corahnrin%'
        maps:
            resource: '@EsterenMaps/maps-layout.html.twig'
            host: '%esteren_domains.esterenmaps%'
        front:
            resource: 'cms_page_layout.html.twig'
