
# Use PierstovalCharacterManager to setup CorahnRin's character generator.
# This bundle has to be standalone as much as possible, to only use config and/or override.
# Services are in "src/CorahnRin/CorahnRinBundle/Resources/config/steps.yml"
pierstoval_character_manager:
    character_class: 'CorahnRin\CorahnRinBundle\Entity\Characters'
    steps:

        01_people:
            action: CorahnRin\CorahnRinBundle\Step\Step01People

        02_job:
            action: CorahnRin\CorahnRinBundle\Step\Step02Job
            onchange_clear:
                - '13_primary_domains'
                - '14_use_domain_bonuses'
                - '15_domains_spend_exp'
                - '16_disciplines'
                - '17_combat_arts'

        03_birthplace:
            action: CorahnRin\CorahnRinBundle\Step\Step03Birthplace

        04_geo:
            action: CorahnRin\CorahnRinBundle\Step\Step04Geo
            onchange_clear:
                - '14_use_domain_bonuses'

        05_social_class:
            action: CorahnRin\CorahnRinBundle\Step\Step05SocialClass
            onchange_clear:
                - '14_use_domain_bonuses'

        06_age:
            action: CorahnRin\CorahnRinBundle\Step\Step06Age
            onchange_clear:
                - '07_setbacks'
                - '14_use_domain_bonuses'

        07_setbacks:
            action: CorahnRin\CorahnRinBundle\Step\Step07Setbacks
            depends_on:
                - '06_age'

        08_ways:
            action: CorahnRin\CorahnRinBundle\Step\Step08Ways
            onchange_clear:
                - '09_traits'
                - '10_orientation'
                - '17_combat_arts'

        09_traits:
            action: CorahnRin\CorahnRinBundle\Step\Step09Traits
            depends_on:
                - '08_ways'

        10_orientation:
            action: CorahnRin\CorahnRinBundle\Step\Step10Orientation
            depends_on:
                - '08_ways'

        11_advantages:
            action: CorahnRin\CorahnRinBundle\Step\Step11Advantages
            onchange_clear:
                - '13_primary_domains'
                - '14_use_domain_bonuses'
                - '15_domains_spend_exp'
                - '16_disciplines'
                - '17_combat_arts'

        12_mental_disorder:
            action: CorahnRin\CorahnRinBundle\Step\Step12MentalDisorder
            depends_on:
                - '08_ways'

        13_primary_domains:
            action: CorahnRin\CorahnRinBundle\Step\Step13PrimaryDomains
            depends_on:
                - '02_job'
                - '11_advantages'
            onchange_clear:
                - '14_use_domain_bonuses'
                - '15_domains_spend_exp'
                - '16_disciplines'
                - '17_combat_arts'

        14_use_domain_bonuses:
            action: CorahnRin\CorahnRinBundle\Step\Step14UseDomainBonuses
            depends_on:
                - '04_geo'
                - '05_social_class'
                - '13_primary_domains'
            onchange_clear:
                - '15_domains_spend_exp'
                - '16_disciplines'

        15_domains_spend_exp:
            action: CorahnRin\CorahnRinBundle\Step\Step15DomainsSpendExp
            depends_on:
                - '14_use_domain_bonuses'
            onchange_clear:
                - '16_disciplines'

        16_disciplines:
            action: CorahnRin\CorahnRinBundle\Step\Step16Disciplines
            depends_on:
                - '15_domains_spend_exp'

        17_combat_arts:
            action: CorahnRin\CorahnRinBundle\Step\Step17CombatArts
            depends_on:
                - '15_domains_spend_exp'

        18_equipment:
            action: CorahnRin\CorahnRinBundle\Step\Step18Equipment

        19_description:
            action: CorahnRin\CorahnRinBundle\Step\Step19Description

        20_finish:
            action: CorahnRin\CorahnRinBundle\Step\Step20Finish

services:
    _defaults:
        autowire: true
        bind:
            $tileSize: '%esterenmaps.tile_size%'

    CorahnRin\CorahnRinBundle\Step\:
        resource: ../../src/CorahnRin/CorahnRinBundle/Step
