# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    # http://symfony.com/doc/current/security.html#hierarchical-roles
    role_hierarchy:

        # Anyone who is a backer from Kickstarter or Ulule.
        ROLE_BACKER: ROLE_USER

        # A user that can view the map is automatically a user.
        ROLE_MAPS_VIEW: ROLE_USER

        # Backers "Travels" reedition
        ROLE_BACKER_TRAVELS:
            - ROLE_BACKER
            - ROLE_MAPS_VIEW

        # Content managers (access to backend)
        ROLE_MANAGER:                   ROLE_USER

        # Maps
        ROLE_ADMIN_MAPS:                ROLE_MANAGER

        # Character Generator
        ROLE_ADMIN_GENERATOR:           ROLE_MANAGER

        # Translator
        ROLE_ADMIN_TRANSLATOR:          ROLE_MANAGER

        # Admins
        ROLE_ADMIN:
            - ROLE_MANAGER
            - ROLE_ADMIN_GENERATOR
            - ROLE_ADMIN_MAPS
            - ROLE_ADMIN_TRANSLATOR
        ROLE_SUPER_ADMIN:
            - ROLE_BACKER_TRAVELS
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            id: Agate\Security\Provider\UsernameOrEmailProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  '^/(_(profiler|wdt)|css|images|img|fonts|map_tiles|uploads|components|bundles|js|(%locales_regex%)/js/translations)/'
            security: false

        # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
        # http://symfony.com/doc/current/security/form_login_setup.html
        main:
            pattern: ^/
            anonymous: ~
            logout_on_user_change: true # Todo: remove this when migrating to Symfony 4
            remember_me:
                secret: '%env(APP_SECRET)%'
                path: /
                name: EsterenRememberMe
            logout:
                invalidate_session: false
                path: user_logout
                target: root
            guard:
                authenticators:
                    - Agate\Security\FormLoginAuthenticator

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/security.html#security-book-access-control-matching-options
    access_control:
        - { path: '^/(?:%locales_regex%)/login$',     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(?:%locales_regex%)/register',   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(?:%locales_regex%)/resetting',  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(?:%locales_regex%)/profile',    roles: [ROLE_USER] }
        - { path: '^/(?:%locales_regex%)/characters', roles: [ROLE_USER] }
        - { path: '^/',                               host: '%esteren_domains.backoffice%',   role: ROLE_MANAGER }
