# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: bcrypt

    # http://symfony.com/doc/current/security.html#hierarchical-roles
    role_hierarchy:

        # Admins
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            id: User\Repository\UserRepository

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  '^/(_(profiler|wdt)|css|images|img|fonts|map_tiles|uploads|components|bundles|js|(%locales_regex%)/js/translations)/'
            security: false

        # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
        # http://symfony.com/doc/current/security/form_login_setup.html
        main:
            pattern: ^/
            anonymous: ~
            provider: user_provider
            remember_me:
                secret: '%env(APP_SECRET)%'
                path: /
                name: EsterenRememberMe
            logout:
                invalidate_session: false
                path: user_logout
                target: root
            guard:
                authenticators:
                    - User\Security\FormLoginAuthenticator

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/security.html#security-book-access-control-matching-options
    access_control:
        - { path: '^/(?:%locales_regex%)/login',      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(?:%locales_regex%)/register',   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(?:%locales_regex%)/resetting',  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/(?:%locales_regex%)/profile',    role: ROLE_USER }
        - { path: '^/',                               host: '%esteren_domains.backoffice%',  role: ROLE_ADMIN }
