assets:
    esteren_general_less:
        type: less
        sources:
            - src/Esteren/PortalBundle/Resources/public/less/_main.less
        output: main_less.css
    esteren_maps_less:
        type: less
        sources:
            - src/EsterenMaps/MapsBundle/Resources/public/css/maps.less
        output: maps_lib.css
    esteren_general_css:
        type: css
        sources:
            - web/components/leaflet/dist/leaflet.css
            - web/components/leaflet-draw/dist/leaflet.draw.css
            - web/components/leaflet-sidebar/src/L.Control.Sidebar.css
            - web/css/main_less.css
        output: global.css
    esteren_general_js:
        type: js
        sources:
            - web/components/bootstrap/js/button.js
            - web/components/bootstrap/js/collapse.js
            - web/components/bootstrap/js/dropdown.js
            - web/components/bootstrap/js/modal.js
            - web/components/bootstrap/js/tooltip.js
            - web/components/bootstrap/js/popover.js
            - web/components/bootstrap/js/transition.js
            - web/components/bootstrap/js/tab.js
            - src/Esteren/PortalBundle/Resources/public/js/corahn_rin.js
        output: global.js
    esteren_maps_js:
        type: js
        sources:
            - web/components/leaflet/dist/leaflet-src.js
            - web/components/leaflet-sidebar/src/L.Control.Sidebar.js
            - web/components/leaflet-draw/dist/leaflet.draw-src.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/1_EsterenMap.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/2_LeafletDrawOverrides.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/2_EsterenMap_directions.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/3_EsterenMap_options.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/3_EsterenMap_ActivateLeafletDraw.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addMarker.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addPolyline.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addPolygon.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_filters.js
        output: maps_lib.js
    esterenmaps_edit_js:
        type: js
        sources:
            - src/EsterenMaps/MapsBundle/Resources/public/js/map_edit.js
        output: map_edit_more.js
