
revisions_temp_directory: app/cache

manifest_file: app/cache/rev-manifest.yml

assets:

    fontawesome:
        type: less
        sources:
            - src/Esteren/PortalBundle/Resources/public/less/_fontawesome.less
        output: css/fontawesome.css

    esteren_general_less:
        type: less
        sources:
            - src/Esteren/PortalBundle/Resources/public/less/_main.less
        output: css/main_less.css

    esteren_maps_less:
        type: less
        sources:
            - src/EsterenMaps/MapsBundle/Resources/public/css/maps.less
        output: css/maps_less.css

    esteren_maps_css:
        type: css
        sources:
            - web/components/leaflet/dist/leaflet.css
            - web/components/leaflet-draw/dist/leaflet.draw.css
            - web/components/leaflet-sidebar/src/L.Control.Sidebar.css
            - web/css/maps_less.css
        output: css/maps_lib.css

    esteren_general_css:
        type: css
        sources:
            - web/css/main_less.css
        output: css/global.css

    esteren_general_js:
        type: js
        sources:
            - web/components/bootstrap/js/button.js
            - web/components/bootstrap/js/collapse.js
            - web/components/bootstrap/js/dropdown.js
            - web/components/bootstrap/js/modal.js
            - web/components/bootstrap/js/tooltip.js
            - web/components/bootstrap/js/popover.js
            - web/components/bootstrap/js/transition.js
            - web/components/bootstrap/js/tab.js
            - src/Esteren/PortalBundle/Resources/public/js/corahn_rin.js
        output: js/global.js

    esteren_maps_js:
        type: js
        sources:
            - web/components/leaflet/dist/leaflet-src.js
            - web/components/leaflet-sidebar/src/L.Control.Sidebar.js
            - web/components/leaflet-draw/dist/leaflet.draw-src.js
            - src/EsterenMaps/MapsBundle/Resources/public/js/EsterenMap/*.js
        output: js/maps_lib.js

    esterenmaps_edit_js:
        type: js
        sources:
            - src/EsterenMaps/MapsBundle/Resources/public/js/map_edit.js
        output: js/map_edit_more.js

    generator_js:
        type: js
        sources:
            - '@CorahnRinBundle/Resources/public/generator/js/*.js'
        output: 'js/generator.js'

    generator_css:
        type: css
        sources:
            - '@CorahnRinBundle/Resources/public/generator/css/*.css'
        output: "css/generator.css"
