
exclude_patterns:
    - src/CorahnRin/CorahnRinBundle/PDF/FPDF.php
    - src/CorahnRin/CorahnRinBundle/SheetsManagers/PdfManager.php
    - src/CorahnRin/CorahnRinBundle/Command/ImportLegacyCharactersCommand.php
    - bin/symfony_requirements
    - web/app_*.php

rules:
    symfony.form.form_type_not_in_type_form_folder:
        enabled: false
