php_version: 7.1

pre_composer_script: |
    #!/bin/bash
    # Hope it'll be easier in the future...
    cp .env.test .env
    yes '' | pecl install apcu

post_composer_script: |
    #!/bin/bash
    source .env
    mkdir build/
    php tests/bootstrap.php

php_ini: |
    extension=apcu
    extension=curl
    extension=gd
    extension=iconv
    extension=intl
    extension=mbstring
    extension=pdo_mysql
    extension=openssl

exclude_patterns:
    - src/CorahnRin/PDF/FPDF.php
    - src/CorahnRin/PDF/PDF.php
    - src/CorahnRin/SheetsManagers/PdfManager.php
    - src/CorahnRin/Command/ImportLegacyCharactersCommand.php
    - public/index.php
    - config/bootstrap.php

rules:
    symfony.controller.missing_redirect_after_post: { enabled: false }
    symfony.form.form_type_not_in_type_form_folder: { enabled: false }
    twig.template_too_complex: { enabled: false }
    task_todo_comment: { enabled: false }
    php.interface_has_no_interface_suffix: { enabled: false }
    symfony.controller.action_method_too_long:
        max_length: 30
