
pre_composer_script: |
    #!/bin/bash

    export SYMFONY_ENV=test
    export SYMFONY_DEBUG=1

    # Do what you need to setup your project
    rm web/config.php
    cp app/config/parameters.yml.dist app/config/parameters.yml
    cp .env.dist .env

post_composer_script: |
    #!/bin/bash

    # Do what you need to configure your project
    ./app/console doctrine:database:create --no-interaction
    ./app/console doctrine:schema:create --no-interaction
    ./app/console doctrine:fixtures:load --no-interaction

exclude_patterns:
    - src/CorahnRin/CorahnRinBundle/PDF/FPDF.php
    - src/CorahnRin/CorahnRinBundle/SheetsManagers/PdfManager.php
    - src/CorahnRin/CorahnRinBundle/Command/ImportLegacyCharactersCommand.php
    - bin/symfony_requirements
    - web/app_*.php

rules:
    symfony.form.form_type_not_in_type_form_folder:
        enabled: false
