name: agate

type: php:7.3

runtime:
    extensions:
        - apcu
        - mbstring
        - json
        - apcu
        - gd
        - intl
        - curl

relationships:
    database: "mysql:main"
    database_legacy: "mysql:main"

build:
    flavor: none

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

disk: 2048

dependencies:
    nodejs: {}

mounts:
    "/var": "shared:files/var"

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)

        npm install

        npm run deploy

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

        bin/console doctrine:migrations:migrate --no-interaction
