sudo: required

language: php

services:
    - docker

cache:
    directories:
        - $HOME/.composer/
        - $HOME/.npm/

env:
    - DOCKER_COMPOSE_VERSION=1.22.0

jobs:
    include:
        - name: PHP
          before_cache: 'test -d $HOME/.composer/ || mkdir $HOME/.composer'
          before_install:
              - sudo rm /usr/local/bin/docker-compose
              - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
              - chmod +x docker-compose
              - sudo mv docker-compose /usr/local/bin
              - make install-php
          script: make php-tests
          after_failure:
              - git status
              - cat var/log/test.log
              - cat var/log/panther.log
              - ls -lah build/log/*
              - cat build/log/*
          after_success:
              - make phpunit-coverage
              - cat build/log/coverage.xml

        - name: NodeJS
          before_cache: 'test -d $HOME/.npm/ || mkdir $HOME/.npm'
          before_install:
              - sudo rm /usr/local/bin/docker-compose
              - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
              - chmod +x docker-compose
              - sudo mv docker-compose /usr/local/bin
              - make install-node
          script: make node-tests
