version: '3'

services:
    php:
        # Docker build here:
        # https://hub.docker.com/r/pierstoval/studio-agate-portal/
        # https://github.com/StudioAgate/DockerPortalApp
        image: 'pierstoval/studio-agate-portal:v0.2.1'
        volumes:
            - ./:/var/www/html
        links:
            - db
            - mailcatcher
        environment:
            - IMAGEMAGICK_BINARIES_PATH=/usr/bin/magick
            - AGATE_DOMAIN=studio-agate.docker
            - DRAGONS_DOMAIN=dragons-rpg.docker
            - ESTEREN_DOMAIN=esteren.docker
            - VERMINE_DOMAIN=vermine2047.docker
            - DATABASE_URL=mysql://root:agate_portal@db/agate_portal?serverVersion=10.1
            - DATABASE_URL_LEGACY=mysql://root:esteren_legacy@db_legacy/esteren_legacy?serverVersion=10.1
            - MAILER_URL=smtp://mailcatcher

    mailcatcher:
        image: tophfr/mailcatcher:latest
        ports:
            - '1080:80'

    node:
        image: node:8
        volumes:
            - ./:/var/www/html
        command: 'npm --cwd /var/www/html run gulp watch'

    nginx:
        build: ./docker/nginx/
        working_dir: /var/www/html/
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php

    db:
        image: 'mariadb:10.1'
        environment:
            - MYSQL_ROOT_PASSWORD=agate_portal
            - MYSQL_DATABASE=agate_portal

    db_legacy:
        image: 'mariadb:10.1'
        environment:
            - MYSQL_ROOT_PASSWORD=esteren_legacy
            - MYSQL_DATABASE=esteren_legacy
