version: '3'

services:
    php:
        # Docker build here:
        # https://hub.docker.com/r/pierstoval/studio-agate-portal/
        # https://github.com/StudioAgate/DockerPortalApp
        image: 'pierstoval/studio-agate-portal:v0.2.2'
        working_dir: /srv/
        volumes:
            - ./:/srv
        links:
            - db
            - mailcatcher

    mailcatcher:
        image: tophfr/mailcatcher:latest
        ports:
            - '1080:80'

    node:
        build: ./docker/node/
        working_dir: /srv/
        volumes:
            - ./:/srv/
        command: 'npm run gulp watch'

    nginx:
        build: ./docker/nginx/
        working_dir: /srv/
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./:/srv/

    db:
        image: 'mariadb:10.1'
        environment:
            - MYSQL_ROOT_PASSWORD=agate_portal
            - MYSQL_DATABASE=agate_portal

    db_legacy:
        image: 'mariadb:10.1'
        environment:
            - MYSQL_ROOT_PASSWORD=esteren_legacy
            - MYSQL_DATABASE=esteren_legacy
