version: '2'

services:
    php:
        # Docker build here:
        # https://hub.docker.com/r/pierstoval/studio-agate-portal/
        # https://github.com/StudioAgate/DockerPortalApp
        image: 'pierstoval/studio-agate-portal:v0.2.0'
        volumes:
            - ./:/var/www/html
        links:
            - db

    node:
        image: node:9
        volumes_from:
            - php
        command: 'yarn --cwd /var/www/html run gulp watch'

    nginx:
        build: ./docker/nginx/
        working_dir: /var/www/html/
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php

    db:
        image: 'mariadb:10.1'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: esteren_portal
            MYSQL_DATABASE: esteren_portal
            MYSQL_USER: esteren_portal
            MYSQL_PASSWORD: esteren_portal
