version: '2'

services:
    php:
        # Docker build here:
        # https://hub.docker.com/r/pierstoval/studio-agate-portal/
        # https://github.com/StudioAgate/DockerPortalApp
        image: 'pierstoval/studio-agate-portal:v0.2.1'
        volumes:
            - ./:/var/www/html
        links:
            - db
        environment:
            - APP_ENV=dev
            - AGATE_DOMAIN=studio-agate.piers
            - DRAGONS_DOMAIN=dragons-rpg.piers
            - ESTEREN_DOMAIN=esteren.piers
            - VERMINE_DOMAIN=vermine2047.piers
            - DATABASE_URL="mysql://esteren_portal:esteren_portal@esteren_portal/esteren_portal?serverVersion=10.1"

    node:
        image: node:8
        volumes_from:
            - php
        command: 'npm --cwd /var/www/html run gulp watch'

    nginx:
        build: ./docker/nginx/
        working_dir: /var/www/html/
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php

    db:
        image: 'mariadb:10.1'
        ports:
            - '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: esteren_portal
            MYSQL_DATABASE: esteren_portal
            MYSQL_USER: esteren_portal
            MYSQL_PASSWORD: esteren_portal
