version: '3'

volumes:
    node_modules:

services:
    php:
        # Docker build here:
        # https://hub.docker.com/r/pierstoval/studio-agate-portal/
        # https://github.com/StudioAgate/DockerPortalApp
        image: 'pierstoval/studio-agate-portal:latest'
        working_dir: /srv/
        volumes:
            - ./:/srv
            - ~/.composer/cache:/root/.composer/cache
        links:
            - db
            - mailcatcher
            - blackfire
        environment:
            - BLACKFIRE_SOCKET=tcp://blackfire:8707

    blackfire:
        image: blackfire/blackfire

    mailcatcher:
        image: tophfr/mailcatcher:latest
        ports:
            - '1080:80'

    node:
        build: ./docker/node/
        working_dir: /srv/
        volumes:
            - .:/srv
            - node_modules:/srv/node_modules/
            - ~/.npm/:/root/.npm
        command: 'sleep 99999d'

    nginx:
        build: ./docker/nginx/
        working_dir: /srv/
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./:/srv/

    # Dump can be saved in var/ that's why it's the only directory we share
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOSTS=db
        ports:
            - 8081:80
        links:
            - db

    db:
        image: 'mysql:5.7'
        working_dir: /srv/
        ports:
            - '13306:3306'
        volumes:
            - ./var/:/srv/
        environment:
            - MYSQL_ROOT_PASSWORD=db

    qa:
        image: jakzal/phpqa:php7.2
        command: 'sleep 99999d'
        working_dir: /srv/
        volumes:
            - ./:/srv/
