version: '3'

services:
    php:
        # Docker build here:
        # https://hub.docker.com/r/pierstoval/studio-agate-portal/
        # https://github.com/StudioAgate/DockerPortalApp
        image: 'pierstoval/studio-agate-portal:latest'
        working_dir: /srv/
        volumes:
            - ./:/srv
            - ~/.composer/cache:/root/.composer/cache
        links:
            - db
            - mailcatcher

    mailcatcher:
        image: tophfr/mailcatcher:latest
        ports:
            - '1080:80'

    node:
        build: ./docker/node/
        working_dir: /srv/
        volumes:
            - ./:/srv/
            - ~/.npm/:/root/.npm
        command: 'npm run gulp watch'

    nginx:
        build: ./docker/nginx/
        working_dir: /srv/
        ports:
            - '8080:80'
        links:
            - php
        volumes:
            - ./:/srv/

    # Dump can be saved in var/ that's why it's the only directory we share
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOSTS=db,db_legacy
        restart: always
        ports:
            - 8081:80
        links:
            - db
            - db_legacy

    db:
        image: 'mysql:5.7'
        working_dir: /srv/
        volumes:
            - ./var/:/srv/
        environment:
            - MYSQL_ROOT_PASSWORD=agate_portal
            - MYSQL_DATABASE=agate_portal

    db_legacy:
        image: 'mysql:5.7'
        environment:
            - MYSQL_ROOT_PASSWORD=esteren_legacy
            - MYSQL_DATABASE=esteren_legacy
