easy_admin:
    entities:

        ####################
        ## Orbitale CMS
        Pages:
            label: admin.cms.pages
            class: Esteren\PortalBundle\Entity\Page
            show:
                fields: [ id, parent, title, slug, tree, content, metaDescription, metaTitle, category, host, locale, homepage, enabled ]
            list:
                actions:
                    - { name: 'admin_page_preview', label: 'page.preview.admin_link', icon: 'search', type: route }
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: parent, label: 'admin.entities.pages.parent' }
                    - { property: title, label: 'admin.entities.pages.title' }
                    - { property: slug, label: 'admin.entities.common.slug' }
                    - { property: tree, label: 'admin.entities.pages.tree' }
                    - { property: host, label: 'admin.entities.pages.host' }
                    - { property: locale, label: 'admin.entities.pages.locale' }
                    - { property: homepage, label: 'admin.entities.pages.homepage', type: boolean }
                    - { property: enabled, label: 'admin.entities.pages.enabled', type: boolean }

            form:
                fields:
                    # Right panel with general informations
                    - { type: 'group', css_class: 'col-sm-7' }
                    - { type: 'section', label: 'admin.sections.general' }
                    - { property: title, label: 'admin.entities.pages.title' }
                    - { property: slug, label: 'admin.entities.common.slug' }
                    - { property: content, label: 'admin.entities.pages.content', type: ckeditor }

                    - property: host
                      label: 'admin.entities.pages.host'
                      type: choice
                      type_options:
                          choices:
                              '%esteren_domains.games%': '%esteren_domains.games%'
                              '%esteren_domains.portal%': '%esteren_domains.portal%'
                              '%esteren_domains.corahnrin%': '%esteren_domains.corahnrin%'

                    - property: locale
                      label: 'admin.entities.pages.locale'
                      type: choice
                      type_options:
                          choices: '%locales%'
                          choice_translation_domain: Languages

                    - { property: homepage, label: 'admin.entities.pages.homepage' }
                    - { property: enabled, label: 'admin.entities.pages.enabled' }
                    - { property: showTitle, label: 'admin.entities.pages.show_title' }

                    # Left panel with other sections
                    - { type: 'group', css_class: 'col-sm-5 right' }

                    - { type: 'section', label: 'admin.sections.seo' }
                    - { property: metaDescription, label: 'admin.entities.pages.meta_description' }
                    - { property: metaTitle, label: 'admin.entities.pages.meta_title' }
                    - { property: metaKeywords, label: 'admin.entities.pages.meta_keywords' }

                    - { type: 'section', label: 'admin.sections.design' }
                    - property: template
                      label: 'admin.entities.pages.template'
                      type: choice
                      type_options:
                          required: true
                          choices:
                              'templates.base': 'base.html.twig'
                              'templates.material': 'base_materialize.html.twig'
                    - { property: css, label: 'admin.entities.pages.css' }
                    - { property: js, label: 'admin.entities.pages.js' }
                    - { property: containerCssClass, label: 'admin.entities.pages.container_css_class' }

                    - { type: 'section', label: 'admin.sections.associations' }
                    - { property: category, label: 'admin.entities.pages.category' }
                    - { property: parent, label: 'admin.entities.pages.parent' }
