easy_admin:
    entities:

        ####################
        ## Orbitale CMS
        "Pages":
            label: admin.cms.pages
            class: Esteren\PortalBundle\Entity\Page
            show:
                fields: [ id, parent, title, slug, tree, content, metaDescription, metaTitle, category, host, locale, homepage, enabled ]
            list:
                fields:
                    - id
                    - parent
                    - title
                    - slug
                    - tree
                    - host
                    - locale
                    - { property: homepage, type: boolean }
                    - { property: enabled, type: boolean }
            form:
                fields:
                    - title
                    - slug
                    - { property: content, type: 'Ivory\CKEditorBundle\Form\Type\CKEditorType' }
                    - metaDescription
                    - metaTitle
                    - metaKeywords
                    - css
                    - js
                    - category
                    - parent
                    - property: host
                      type: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                      type_options:
                          choices:
                              - "%esteren_domains.games%"
                              - "%esteren_domains.portal%"
                              - "%esteren_domains.corahnrin%"

                    - homepage
                    - enabled
