easy_admin:
    entities:

        ####################
        ## Esteren Maps
        Factions:
            label: admin.maps.factions
            class: EsterenMaps\MapsBundle\Entity\Factions
            list:
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: book, label: 'admin.entities.common.book' }

            form:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: book, label: 'admin.entities.common.book' }

        Maps:
            label: admin.maps.maps
            class: EsterenMaps\MapsBundle\Entity\Maps
            list:
                actions:
                    - edit
                    - { name: admin_esterenmaps_maps_maps_editInteractive, type: route, label: actions.interactive  }
                    - '-delete'
                fields:
                    - { property: id, label: 'admin.entities.common.id' }
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: nameSlug, label: 'admin.entities.common.nameSlug' }
                    - { property: maxZoom, label: 'admin.entities.factions.maxZoom' }
                    - { property: startZoom, label: 'admin.entities.factions.startZoom' }
                    - { property: startX, label: 'admin.entities.factions.startX' }
                    - { property: startY, label: 'admin.entities.factions.startY' }
            new:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: nameSlug, label: 'admin.entities.common.nameSlug' }
                    - { property: image, label: 'admin.entities.factions.image' }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: maxZoom, label: 'admin.entities.factions.maxZoom' }
                    - { property: bounds, label: 'admin.entities.factions.bounds' }
                    - { property: startZoom, label: 'admin.entities.factions.startZoom' }
                    - { property: startX, label: 'admin.entities.factions.startX' }
                    - { property: startY, label: 'admin.entities.factions.startY' }
                    - { property: coordinatesRatio, label: 'admin.entities.factions.coordinatesRatio' }
            edit:
                fields:
                    - { property: name, label: 'admin.entities.common.name' }
                    - { property: nameSlug, label: 'admin.entities.common.nameSlug', type_options: { disabled: true, required: false } }
                    - { property: image, label: 'admin.entities.factions.image', type_options: { disabled: true, required: false } }
                    - { property: description, label: 'admin.entities.common.description' }
                    - { property: maxZoom, label: 'admin.entities.factions.maxZoom' }
                    - { property: bounds, label: 'admin.entities.factions.bounds' }
                    - { property: startZoom, label: 'admin.entities.factions.startZoom' }
                    - { property: startX, label: 'admin.entities.factions.startX' }
                    - { property: startY, label: 'admin.entities.factions.startY' }
                    - { property: coordinatesRatio, label: 'admin.entities.factions.coordinatesRatio' }

        Markers:
            label: admin.maps.markers
            class: EsterenMaps\MapsBundle\Entity\Markers
            list:
                actions:
                    - '-delete'
                fields:
                    - id
                    - name
                    - latitude
                    - longitude
                    - markerType
                    - property: webIcon
                      type: image
            form:
                fields:
                    - property: name
                      type_options:
                          required: true
                    - description
                    - markerType
                    - faction
                    - property: latitude
                      type_options: { disabled: true, required: false }

                    - property: longitude
                      type_options: { disabled: true, required: false }

                    - property: altitude
                      type_options: { disabled: true, required: false }

                    - property: map
                      type_options: { disabled: true, required: false }

        MarkersTypes:
            label: admin.maps.markers_types
            class: EsterenMaps\MapsBundle\Entity\MarkersTypes
            list:
                actions:
                    - '-delete'
                fields:
                    - id
                    - name
                    - { property: webIcon, type: image, virtual: false } # FIXME
                    - markers
            form:
                fields: [ name, icon, markers ]

        Routes:
            label: admin.maps.routes
            class: EsterenMaps\MapsBundle\Entity\Routes
            list:
                actions:
                    - '-delete'
                fields:
                    - id
                    - name
                    - distance
                    - description
                    - routeType
                    - markerStart
                    - markerEnd
            form:
                fields:
                    - { property: name, type_options: { required: true } }
                    - description
                    - markerStart
                    - markerEnd
                    - routeType
                    - faction
                    - guarded
                    - { property: coordinates, type_options: { disabled: true, required: false } }
                    - { property: map,         type_options: { disabled: true, required: false } }

        RoutesTypes:
            label: admin.maps.routes_types
            class: EsterenMaps\MapsBundle\Entity\RoutesTypes
            list:
                actions:
                    - '-delete'
                fields: [ id, name, color, routes ]
            form:
                fields: [ name, color ]

        Zones:
            label: admin.maps.zones
            class: EsterenMaps\MapsBundle\Entity\Zones
            list:
                actions:
                    - '-delete'
                fields:
                    - id
                    - name
                    - description
                    - zoneType
                    - map
                    - faction
            form:
                fields:
                    - property: name
                      type_options:
                          required: true
                    - description
                    - zoneType
                    - faction
                    - property: coordinates
                      type_options:
                          disabled: true
                          required: false
                          attr: { readonly: readonly }
                    - property: map
                      type_options:
                          disabled: true
                          required: false
                          attr: { readonly: readonly }

        ZonesTypes:
            label: admin.maps.zones_types
            class: EsterenMaps\MapsBundle\Entity\ZonesTypes
            list:
                actions:
                    - '-delete'
                fields: [ id, name, color, parent, zones ]
            form:
                fields: [ name, color, parent ]

        TransportTypes:
            label: admin.maps.transports_types
            class: EsterenMaps\MapsBundle\Entity\TransportTypes
            controller: EsterenMaps\MapsBundle\Controller\Admin\TransportTypesController
            list:
                actions:
                    - '-delete'
                fields: [ id, name, slug, { property: speed, format: '%.2f' }, description ]
            form:
                fields:
                  - name
                  - slug
                  - { property: speed, help: '(Km/h)' }
                  - description
                  - property: transportsModifiers
                    type: 'Symfony\Component\Form\Extension\Core\Type\CollectionType'
                    type_options:
                        entry_type: 'EsterenMaps\MapsBundle\Form\TransportModifiersType'
