CorahnRin\ModelsBundle\Entity\Jobs:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        book:
            - NotNull: ~
            - Type: CorahnRin\ModelsBundle\Entity\Books
        domainPrimary:
            - NotNull: ~
            - Type: CorahnRin\ModelsBundle\Entity\Domains