CorahnRin\ModelsBundle\Entity\Ogham:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        book:
            - NotNull: ~
            - Type: CorahnRin\ModelsBundle\Entity\Books
        oghamType:
            - NotNull: ~
            - Type: CorahnRin\ModelsBundle\Entity\OghamTypes