CorahnRin\ModelsBundle\Entity\Peoples:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        book:
            - NotNull: ~
            - Type: CorahnRin\ModelsBundle\Entity\Books