CorahnRin\ModelsBundle\Entity\Regions:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        kingdom:
            - NotBlank: ~
            - Type: string
        coordinates:
            - NotBlank: ~
            - Type: string
        book:
            - NotNull: ~
            - Type: CorahnRin\ModelsBundle\Entity\Books