CorahnRin\ModelsBundle\Entity\Traits:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        nameFemale:
            - NotBlank: ~
            - Type: string
        way:
            - NotNull: ~
            - Type: CorahnRin\ModelsBundle\Entity\Ways