parameters:
    esterenmaps.tile_size: 168
    esterenmaps.output_directory: "%kernel.root_dir%/../web/maps_tiles/"
    esterenmaps.directions.cache_dir: "%kernel.cache_dir%/esterenmaps/directions/"
    esterenmaps.directions.cache_ttl: 3600

services:

    esteren_maps:
        class: EsterenMaps\MapsBundle\Services\MapsRegistry
        arguments:
            - "@esterenmaps.directions_manager"
            - "@esterenmaps.map_image_manager"
            - "@esterenmaps.tiles_manager"
            - "@esterenmaps.coordinates_manager"

    esterenmaps.tiles_manager:
        class: EsterenMaps\MapsBundle\Services\MapsTilesManager
        public: false
        lazy: true
        arguments:
            - "%esterenmaps.output_directory%"
            - "%esterenmaps.tile_size%"
            - "%magick_binaries_path%"
            - "@esterenmaps.map_image_manager"
            - "@kernel"

    esterenmaps.map_image_manager:
        class: EsterenMaps\MapsBundle\Services\MapImageManager
        public: false
        lazy: true
        arguments:
            - "%esterenmaps.output_directory%"
            - "%magick_binaries_path%"
            - "@doctrine.orm.entity_manager"
            - "@kernel"

    esterenmaps.directions_manager:
        class: EsterenMaps\MapsBundle\Services\DirectionsManager
        public: false
        lazy: true
        arguments:
            - "%esterenmaps.directions.cache_dir%"
            - "%esterenmaps.directions.cache_ttl%"
            - "%kernel.debug%"
            - "@doctrine.orm.default_entity_manager"
            - "@jms_serializer"
            - "@templating"

    esterenmaps.coordinates_manager:
        class: EsterenMaps\MapsBundle\Services\CoordinatesManager
        public: false
        lazy: true

    esterenmaps.subscriber.cache_clear:
        class: EsterenMaps\MapsBundle\DoctrineListeners\CacheClearSubscriber
        arguments:
            - "%esterenmaps.directions.cache_dir%"
        tags:
            - { name: doctrine.event_subscriber, connection: default }
