parameters:
    esterenmaps.tile_size: 168
    esterenmaps.output_directory: '%kernel.project_dir%/public/maps_tiles/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
#        public: false
        bind:
            $debug:           '%kernel.debug%'
            $imageMagickPath: '%magick_binaries_path%'
            $outputDirectory: '%esterenmaps.output_directory%'
            $tile_size:       '%esterenmaps.tile_size%'
            $versionCode:     '%version_code%'
            $versionDate:     '%version_date%'

    EsterenMaps\MapsBundle\Controller\:
        resource: '../../Controller'
        public: true

    EsterenMaps\MapsBundle\Api\:        { resource: '../../Api' }
    EsterenMaps\MapsBundle\Cache\:      { resource: '../../Cache' }
    EsterenMaps\MapsBundle\Repository\: { resource: '../../Repository' }
    EsterenMaps\MapsBundle\Services\:   { resource: '../../Services' }
    EsterenMaps\MapsBundle\Twig\:       { resource: '../../Twig' }

    EsterenMaps\MapsBundle\DoctrineListeners\CacheClearSubscriber:
        tags: [{ name: doctrine.event_subscriber, connection: default }]
