parameters:
    esterenmaps.tile_size: 168
    esterenmaps.output_directory: %kernel.root_dir%/../web/maps_tiles/
    esterenmaps.directions.cache_dir: %kernel.cache_dir%/esterenmaps/directions/
    esterenmaps.directions.cache_ttl: 3600

services:
    esterenmaps.tiles_manager:
        class: EsterenMaps\MapsBundle\Services\MapsTilesManager
        arguments:
            - %esterenmaps.output_directory%
            - %esterenmaps.tile_size%
            - %magick_binaries_path%
            - @esterenmaps.map_image_manager
            - @kernel

    esterenmaps.map_image_manager:
        class: EsterenMaps\MapsBundle\Services\MapImageManager
        arguments:
            - %esterenmaps.output_directory%
            - %magick_binaries_path%
            - @doctrine.orm.entity_manager
            - @kernel

    esterenmaps.directions:
        class: EsterenMaps\MapsBundle\Services\Directions
        arguments:
            - %esterenmaps.directions.cache_dir%
            - %esterenmaps.directions.cache_ttl%
            - %kernel.debug%
            - @doctrine.orm.default_entity_manager
            - @jms_serializer
            - @templating
