#
# Root route that redirects "/" to "/%locale%/"
#
root:
    path: /{locale}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: '/%locale%/'
        permanent: true
        locale: '%locale%'
    requirements:
        locale: '^(?:%locales_regex%)$'
    methods: ['GET']

#
# User
#
user:
    resource: 'user.yaml'
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# CorahnRin
#
corahnrin:
    resource: 'corahnrin.yaml'
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Esteren Maps
# Some controllers use a different domain name, check the @Route annotation on them to be sure.
#
esterenmaps:
    resource: '../../src/EsterenMaps/Controller/'
    type:     annotation
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Agate portal
#
agate:
    resource: '../../src/Agate/Controller/'
    type: annotation
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Esteren portal
#
esteren_portal:
    resource: '../../src/Esteren/Controller/'
    type: annotation
    host: '%esteren_domains.portal%'
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Admin
#
admin:
    resource: 'easy_admin.yaml'
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }
