# Root route that redirects "/" to "/%locale%/"
root:
    path: /{_locale}
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: '/%locale%/'
        permanent: false
        _locale: '%locale%'
    requirements:
        _locale: '^(?:%locales_regex%)$'
    methods: ['GET']

main:
    resource: '_wrapped.yaml'
    prefix: '/{_locale}/'
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '^(?:%locales_regex%)$'
