crowdfunding:
    resource: '../../src/Agate/Controller/Crowdfunding/'
    type: annotation

user_login_check:
    path: /login_check
    methods: ['POST']

user_logout:
    path: /logout
    methods: ['GET', 'POST']

user_security:
    resource: '../../src/Agate/Controller/User/'
    type: annotation
