CorahnRin\CorahnRinBundle\Entity\Peoples:
    properties:
        name:
            - NotBlank: ~
            - Type: string
        book:
            - NotNull: ~
            - Type: CorahnRin\CorahnRinBundle\Entity\Books
