# Why use this file instead of config.yml?
# Well, it's to be sure that we can keep consistency when the Standard Sdition
#  evolves.
# With this structure, we ensure that few modifications made to the new versions
#  of the SE can be reported back to this app without having to make checks
#  through all the config files to seek for "diffs".
# Also, it's better because it keeps "application" config in another file than
#  the "default symfony" config.

imports:
    - { resource: config.yml }
    - { resource: _corahnrin.yml }
    - { resource: _easy_admin.yml }

parameters:
    # The version code is always the last version that was put in production
    version_code: '0.9.3'
    version_date: '09/01/2017'
    locale: fr
    locales:
        fr: fr
        en: en
    locales_regex: 'fr|en'

    # Definition of all subdomains used in the app
    esteren_domains.cookie_domain:      '.%esteren_domain%'
    esteren_domains.portal:       'portal.%esteren_domain%'
    esteren_domains.esterenmaps:    'maps.%esteren_domain%'
    esteren_domains.corahnrin: 'corahnrin.%esteren_domain%'
    esteren_domains.games:         'games.%esteren_domain%'
    esteren_domains.api:             'api.%esteren_domain%'
    esteren_domains.backoffice:     'back.%esteren_domain%'

    google_tags:
        analytics:   'UA-43812649-5'
        tag_manager: 'GTM-T5PQWF'

# Doctrine Configuration
doctrine:
    orm:
        # Override the default repository to get some more good tools
        default_repository_class: Orbitale\Component\DoctrineTools\BaseEntityRepository
        filters:
            # Activate SoftDeleteable for some entities
            # There are some other filters down there
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     '%database_host%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
            legacy:
                driver:   pdo_mysql
                host:     '%database_host_legacy%'
                dbname:   '%database_name_legacy%'
                user:     '%database_user_legacy%'
                password: '%database_password_legacy%'
                charset:  UTF8

framework:
    translator:      { fallbacks: '%locales%' } # Activate translator
    # Add cookie domain as trusted host because requests are made with CORS.
    trusted_hosts:
        - '%esteren_domains.cookie_domain%$'
#        - 127.0.0.1 # To add in dev mode if needed

    session:
        enabled:         true
        cookie_domain:   '%esteren_domains.cookie_domain%'
        name:            EsterenPortal
        cookie_lifetime: 8640000
        gc_maxlifetime:  86400

    # Use version code in assets
    assets:
        version: '%version_code%'

# Twig Configuration
twig:
    globals:
        version_code: '%version_code%'
        version_date: '%version_date%'
        locales: '%locales%'
        locales_regex: '%locales_regex%'
        esteren_domains_corahnrin: '%esteren_domains.corahnrin%'
        esteren_domains_esterenmaps: '%esteren_domains.esterenmaps%'
        esteren_domains_portal: '%esteren_domains.portal%'
        esteren_domains_backoffice: '%esteren_domains.backoffice%'
        esteren_domains_api: '%esteren_domains.api%'
        esteren_domains_cookie_domain: '%esteren_domains.cookie_domain%'
        esteren_domains_games: '%esteren_domains.games%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'form/ckeditor_widget.html.twig'

# Doctrine extensions
# TODO: Implement Translatable
# TODO: Use KnpDoctrineBehaviors instead, more robust
stof_doctrine_extensions:
    default_locale: '%locale%'
    uploadable:
        default_file_path: '%kernel.root_dir%/../web/uploads'
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            uploadable: true
            sluggable: true
            timestampable: true
            softdeleteable: true

# Base FOSUser integration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    UserBundle\Entity\User
    from_email:
        address: "no-reply@%esteren_domain%"
        sender_name: "Esteren team"

# TODO: remove FOSRest integration or refactor it
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/((%locales_regex%)/)?api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }

# JSON beautifier in JMS serializer
jms_serializer:
    visitors:
        json:
            # Corresponds to these constants:
            options:
                - JSON_NUMERIC_CHECK
                - JSON_UNESCAPED_SLASHES      # PHP 5.4+
                - JSON_UNESCAPED_UNICODE      # PHP 5.4+
                - JSON_PRETTY_PRINT           # PHP 5.4+
                - JSON_PRESERVE_ZERO_FRACTION # PHP 5.6+

# Api services
# TODO: Refactor this and use a better method to generate WS based on entities
pierstoval_api:
    allowed_origins:
        - '%esteren_domains.esterenmaps%'
        - '%esteren_domains.corahnrin%'
        - '%esteren_domains.backoffice%'
        - '%esteren_domains.api%'
#        - 127.0.0.1 # To add in dev mode if needed

    services:
        maps:           { entity: EsterenMaps\MapsBundle\Entity\Maps }
        markers:        { entity: EsterenMaps\MapsBundle\Entity\Markers }
        markerstypes:   { entity: EsterenMaps\MapsBundle\Entity\MarkersTypes }
        routes:         { entity: EsterenMaps\MapsBundle\Entity\Routes }
        routestypes:    { entity: EsterenMaps\MapsBundle\Entity\RoutesTypes }
        zones:          { entity: EsterenMaps\MapsBundle\Entity\Zones }
        zonestypes:     { entity: EsterenMaps\MapsBundle\Entity\ZonesTypes }
        transports:     { entity: EsterenMaps\MapsBundle\Entity\TransportTypes }

# This allows using the default layout for Pages and Categories
# See: https://github.com/Orbitale/CmsBundle
orbitale_cms:
    page_class:     Esteren\PortalBundle\Entity\Page
    category_class: Esteren\PortalBundle\Entity\Category
    layouts:
        corahnrin:
            resource: '@CorahnRin/layout.html.twig'
            host: '%esteren_domains.corahnrin%'
        maps:
            resource: '@EsterenMaps/layout.html.twig'
            host: '%esteren_domains.esterenmaps%'
        front:
            resource: 'cms_page_layout.html.twig'

# CORS management for all APIs
nelmio_cors:
    paths:
        '^/':
            allow_credentials: true
            origin_regex: true
            allow_origin:
                - '^(https?://)?%esteren_domains.api%'
                - '^(https?://)?%esteren_domains.corahnrin%'
                - '^(https?://)?%esteren_domains.esterenmaps%'
                - '^(https?://)?%esteren_domains.backoffice%'
            allow_headers: ['Origin','Accept','Content-Type']
            allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
            max_age: 3600
            hosts:
                - '%esteren_domains.api%'

# Used in EasyAdmin's ckeditor fields
ivory_ck_editor:
    input_sync: true
    default_config: base_config
    jquery: true
    jquery_path: ''
    configs:
        base_config:
            language: '%locale%'
            allowedContent: true
            toolbar:
                - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] }
                - { name: 'links',       items: [ 'Link', 'Unlink', 'Anchor' ] }
                - { name: 'insert',      items: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ] }
                - { name: 'tools',       items: [ 'Maximize' ] }
                - '/'
                - { name: 'paragraph',   items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ] }
                - { name: 'styles',      items: [ 'Styles', 'Format' ] }
                - { name: 'document',    items: [ 'Source', '-' ] }
                - { name: 'about',       items: [ 'About' ] }

# Services declaration
services:

    twig.intl_extension:
        class: Twig_Extensions_Extension_Intl
        tags:
            - name: twig.extension
