# Why use this file instead of config.yml?
# Well, it's to be sure that we can keep consistency when the Standard Sdition
#  evolves.
# With this structure, we ensure that few modifications made to the new versions
#  of the SE can be reported back to this app without having to make checks
#  through all the config files to seek for "diffs".
# Also, it's better because it keeps "application" config in another file than
#  the "default symfony" config.

imports:
    - { resource: config.yml }
    - { resource: _easy_admin.yml }

parameters:
    version_code: 0.4.3
    version_date: 02/10/2015
    locale: fr
    locales: [ fr, en ]
    locales_regex: fr|en

    # Map used for step 3 of the character generator
    step_3_map_id: 1

doctrine:
    orm:
        # Override the default repository to get some more good tools
        default_repository_class: Orbitale\Component\DoctrineTools\BaseEntityRepository
    dbal:
        # For eventual sqlite integration, in case of
        driver: %database_driver%
        path: "%database_path%"

framework:
    translator:      { fallbacks: %locales% } # Activate translator
    # Add cookie domain as trusted host because requests are made with CORS
    trusted_hosts:
        - "^[a-z]+\%esteren_domains.cookiedomain%$"

    session:
        cookie_domain: %esteren_domains.cookieDomain%
        name:          EsterenPortal

    # Use version code in assets
    templating:
        assets_version: %version_code%

# Twig Configuration
twig:
    globals:
        version_code: %version_code%
        version_date: %version_date%
        kernel_root_dir: %kernel.root_dir%
        locales: %locales%
        locales_regex: %locales_regex%
        esteren_domains_corahn_rin: %esteren_domains.corahn_rin%
        esteren_domains_esteren_maps: %esteren_domains.esteren_maps%
        esteren_domains_portal: %esteren_domains.portal%
        esteren_domains_backoffice: %esteren_domains.backoffice%
        esteren_domains_api: %esteren_domains.api%
        esteren_domains_cookieDomain: %esteren_domains.cookieDomain%
    form_themes:
        - 'PierstovalToolsBundle:Form:form_div_layout.html.twig'
        - 'PierstovalToolsBundle:Form:fields.html.twig'
        - 'PierstovalToolsBundle:Form:form_errors.html.twig'

# Doctrine Configuration
doctrine:
    orm:
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    UserBundle\Entity\User

# TODO: remove FOSRest integration
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/((%locales_regex%)/)?api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }

# JSON beautifier
jms_serializer:
    visitors:
        json:
            # Corresponds to these constants:
            # JSON_NUMERIC_CHECK | JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE
            options: 480

# Doctrine extensions
# TODO: Implement Translatable
stof_doctrine_extensions:
    default_locale: %locale%
    uploadable:
        default_file_path: %kernel.root_dir%/../web/uploads
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            uploadable: true
            sluggable: true
            timestampable: true
            softdeleteable: true

# Api services
# TODO: Refactor this and use a better method to generate WS based on entities
pierstoval_api:
    allowed_origins:
#        - 127.0.0.1 # Use this in local/dev
        - %esteren_domains.corahn_rin%
        - %esteren_domains.esteren_maps%
        - %esteren_domains.portal%
        - %esteren_domains.backoffice%
        - %esteren_domains.api%
    services:
        maps:           { entity: EsterenMaps\MapsBundle\Entity\Maps }
        markers:        { entity: EsterenMaps\MapsBundle\Entity\Markers }
        markerstypes:   { entity: EsterenMaps\MapsBundle\Entity\MarkersTypes }
        routes:         { entity: EsterenMaps\MapsBundle\Entity\Routes }
        routestypes:    { entity: EsterenMaps\MapsBundle\Entity\RoutesTypes }
        zones:          { entity: EsterenMaps\MapsBundle\Entity\Zones }
        zonestypes:     { entity: EsterenMaps\MapsBundle\Entity\ZonesTypes }
        transports:     { entity: EsterenMaps\MapsBundle\Entity\TransportTypes }

orbitale_cms:
    layouts:
        front:
            resource: "::base.html.twig"

# CORS management
nelmio_cors:
    paths:
      "^/":
          allow_credentials: true
          origin_regex: true
          allow_origin:
#              - 127.0.0.1 # Use this in local/dev
              - ^https?://%esteren_domains.api%
              - ^https?://%esteren_domains.portal%
              - ^https?://%esteren_domains.backoffice%
              - ^https?://%esteren_domains.corahn_rin%
              - ^https?://%esteren_domains.esteren_maps%
          allow_headers: ['Origin','Accept','Content-Type']
          allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
          max_age: 3600
          hosts:
              - 127.0.0.1
              - "^%esteren_domains.api%$"
              - "^%esteren_domains.portal%$"
              - "^%esteren_domains.backoffice%$"
              - "^%esteren_domains.corahn_rin%$"
              - "^%esteren_domains.esteren_maps%$"

# TODO: Remove this and find a better way to handle translations
lexik_translation:
    fallback_locale: %locale%
    managed_locales: %locales%
    base_layout: easy_admin/translation_layout.html.twig

# Used in EasyAdmin's ckeditor fields
ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                - { name: "basicstyles", items: [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat" ] }
                - { name: "links", items: [ "Link", "Unlink", "Anchor" ] }
                - { name: "insert", items: [ "Image", "Table", "HorizontalRule", "SpecialChar" ] }
                - { name: "tools", items: [ "Maximize" ] }
                - '/'
                - { name: "paragraph", items: [ "NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Blockquote" ] }
                - { name: "styles", items: [ "Styles", "Format" ] }
                - { name: "document", items: [ "Source", "-" ] }
                - { name: "about", items: [ "About" ] }

# Services declaration
# TODO: Check if these can be removed safely
services:

    framework_controller:
        class: Symfony\Bundle\FrameworkBundle\Controller\Controller
        calls:
            - [ 'setContainer', [ @service_container ] ]

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
