imports:
    - { resource: config.yml }
    - { resource: _assets.yml }

parameters:
    version_code: 0.2.2
    version_date: 24/07/2015
    locale: fr
    locales: [ fr, en ]
    locales_regex: fr|en
    assetic.filter.uglifyjs.bin: %node_modules_path%uglify-js/bin/uglifyjs
    assetic.filter.uglifycss.bin: %node_modules_path%uglifycss/uglifycss

doctrine:
    orm:
        default_repository_class: Orbitale\Component\DoctrineTools\BaseEntityRepository
    dbal:
        path: "%database_path%" # For eventual sqlite integration

framework:
    translator:      { fallbacks: %locales% } # Activate translator
    trusted_hosts:
        - "^[a-z]+\%esteren_domains.cookiedomain%$"
    session:
        cookie_domain: %esteren_domains.cookieDomain%
        name:   EsterenPortal
    templating:
        assets_version: %version_code%

# Twig Configuration
twig:
    globals:
        version_code: %version_code%
        version_date: %version_date%
        kernel_root_dir: %kernel.root_dir%
        locales: %locales%
        locales_regex: %locales_regex%
        esteren_domains_corahn_rin: %esteren_domains.corahn_rin%
        esteren_domains_esteren_maps: %esteren_domains.esteren_maps%
        esteren_domains_portal: %esteren_domains.portal%
        esteren_domains_backoffice: %esteren_domains.backoffice%
        esteren_domains_api: %esteren_domains.api%
        esteren_domains_cookieDomain: %esteren_domains.cookieDomain%
    form_themes:
        - 'PierstovalToolsBundle:Form:form_div_layout.html.twig'
        - 'PierstovalToolsBundle:Form:fields.html.twig'
        - 'PierstovalToolsBundle:Form:form_errors.html.twig'

assetic:
    node: %node_path%
    node_paths: [ %node_modules_path% ]
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        uglifyjs:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        uglifycss:
            node: %node_path%
            node_paths: [ %node_modules_path% ]

# Doctrine Configuration
doctrine:
    orm:
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    UserBundle\Entity\User

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/((%locales_regex%)/)?api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }

# JSON beautifier
jms_serializer:
    visitors:
        json:
            options: 480

# Doctrine extensions
stof_doctrine_extensions:
    default_locale: %locale%
    uploadable:
        default_file_path: %kernel.root_dir%/../web/uploads
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            uploadable: true
            sluggable: true
            timestampable: true
            softdeleteable: true

# Services declaration
services:
    framework_controller:
        class: Symfony\Bundle\FrameworkBundle\Controller\Controller
        calls:
            - [ 'setContainer', [ @service_container ] ]
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - 'EsterenMapsBundle'
        - 'EsterenPortalBundle'
        - 'CorahnRinBundle'
        - 'EsterenMapsAdminBundle'
        - 'PierstovalTranslationBundle'
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        uglifyjs:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        uglifycss:
            node: %node_path%
            node_paths: [ %node_modules_path% ]

# Api services
pierstoval_api:
    allowed_origins:
        - %esteren_domains.corahn_rin%
        - %esteren_domains.esteren_maps%
        - %esteren_domains.portal%
        - %esteren_domains.backoffice%
        - %esteren_domains.api%
    services:
        maps:           { entity: EsterenMaps\MapsBundle\Entity\Maps }
        markers:        { entity: EsterenMaps\MapsBundle\Entity\Markers }
        markerstypes:   { entity: EsterenMaps\MapsBundle\Entity\MarkersTypes }
        routes:         { entity: EsterenMaps\MapsBundle\Entity\Routes }
        routestypes:    { entity: EsterenMaps\MapsBundle\Entity\RoutesTypes }
        zones:          { entity: EsterenMaps\MapsBundle\Entity\Zones }
        zonestypes:     { entity: EsterenMaps\MapsBundle\Entity\ZonesTypes }
        transports:     { entity: EsterenMaps\MapsBundle\Entity\TransportTypes }

lexik_translation:
    fallback_locale: %locale%
    managed_locales: %locales%
    base_layout: easy_admin/translation_layout.html.twig
