# Why use this file instead of config.yml?
# Well, it's to be sure that we can keep consistency when the Standard Sdition
#  evolves.
# With this structure, we ensure that few modifications made to the new versions
#  of the SE can be reported back to this app without having to make checks
#  through all the config files to seek for "diffs".
# Also, it's better because it keeps "application" config in another file than
#  the "default symfony" config.

imports:
    - { resource: config.yml }
    - { resource: _easy_admin.yml }

parameters:
    # The version code is always the last version that was put in production
    version_code: 0.7.2
    version_date: 11/06/2015
    locale: fr
    locales: [ fr, en ]
    locales_regex: "fr|en"

doctrine:
    orm:
        # Override the default repository to get some more good tools
        default_repository_class: Orbitale\Component\DoctrineTools\BaseEntityRepository
    dbal:
        # For eventual sqlite integration, in case of
        driver: "%database_driver%"
        path: "%database_path%"

framework:
    translator:      { fallbacks: "%locales%" } # Activate translator
    # Add cookie domain as trusted host because requests are made with CORS.
    trusted_hosts:
        - "^[a-z]+\\%esteren_domains.cookie_domain%$"
        # TODO: Add 127.0.0.1 while in dev mode if you need it.

    session:
        cookie_domain: "%esteren_domains.cookie_domain%"
        name:          EsterenPortal

    # Use version code in assets
    assets:
        version: "%version_code%"

# Twig Configuration
twig:
    globals:
        version_code: "%version_code%"
        version_date: "%version_date%"
        locales: "%locales%"
        locales_regex: "%locales_regex%"
        esteren_domains_corahnrin: "%esteren_domains.corahnrin%"
        esteren_domains_esterenmaps: "%esteren_domains.esterenmaps%"
        esteren_domains_portal: "%esteren_domains.portal%"
        esteren_domains_backoffice: "%esteren_domains.backoffice%"
        esteren_domains_api: "%esteren_domains.api%"
        esteren_domains_cookie_domain: "%esteren_domains.cookie_domain%"
    form_themes:
        - "@PierstovalTools/Form/fields.html.twig"
        - "@PierstovalTools/Form/form_errors.html.twig"

# Doctrine Configuration
doctrine:
    orm:
        filters:
            # Activate SoftDeleteable for some entities
            # There are some other filters down there
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Doctrine extensions
# TODO: Implement Translatable
stof_doctrine_extensions:
    default_locale: "%locale%"
    uploadable:
        default_file_path: "%kernel.root_dir%/../web/uploads"
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            uploadable: true
            sluggable: true
            timestampable: true
            softdeleteable: true

# Base FOSUser integration
fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    UserBundle\Entity\User

# TODO: remove FOSRest integration or refactor it
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: "^/((%locales_regex%)/)?api", priorities: ["json", "html"], fallback_format: json, prefer_extension: true }
            - { path: "^/", priorities: [ "html", "*/*"], fallback_format: ~, prefer_extension: true }

# JSON beautifier in JMS serializer
jms_serializer:
    visitors:
        json:
            # Corresponds to these constants:
            options:
                - JSON_NUMERIC_CHECK
                - JSON_UNESCAPED_SLASHES      # PHP 5.4+
                - JSON_UNESCAPED_UNICODE      # PHP 5.4+
                - JSON_PRETTY_PRINT           # PHP 5.4+
                - JSON_PRESERVE_ZERO_FRACTION # PHP 5.6+

# Api services
# TODO: Refactor this and use a better method to generate WS based on entities
pierstoval_api:
    allowed_origins:
        - "%esteren_domains.esterenmaps%"
        - "%esteren_domains.corahnrin%"
        - "%esteren_domains.backoffice%"
        - "%esteren_domains.api%"
        # TODO: Add 127.0.0.1 while in dev mode if you need it.

    services:
        maps:           { entity: EsterenMaps\MapsBundle\Entity\Maps }
        markers:        { entity: EsterenMaps\MapsBundle\Entity\Markers }
        markerstypes:   { entity: EsterenMaps\MapsBundle\Entity\MarkersTypes }
        routes:         { entity: EsterenMaps\MapsBundle\Entity\Routes }
        routestypes:    { entity: EsterenMaps\MapsBundle\Entity\RoutesTypes }
        zones:          { entity: EsterenMaps\MapsBundle\Entity\Zones }
        zonestypes:     { entity: EsterenMaps\MapsBundle\Entity\ZonesTypes }
        transports:     { entity: EsterenMaps\MapsBundle\Entity\TransportTypes }

# This allows using the default layout for Pages and Categories
# See: https://github.com/Orbitale/CmsBundle#using-different-layouts
orbitale_cms:
    layouts:
        front:
            resource: "base.html.twig"
        corahnrin:
            resource: "@CorahnRin/layout.html.twig"
            host: "%esteren_domains.corahnrin%"
        maps:
            resource: "@EsterenMaps/layout.html.twig"
            host: "%esteren_domains.esterenmaps%%"

# Use PierstovalCharacterManager to setup CorahnRin's character generator.
# This bundle has to be standalone as much as possible, to only use config and/or override.
pierstoval_character_manager:
    character_class: CorahnRin\CorahnRinBundle\Entity\Characters
    steps:
        01_people:
            action: corahnrin_generator.steps.step_01
        02_job:
            action: corahnrin_generator.steps.step_02
        03_birthplace:
            action: corahnrin_generator.steps.step_03
        04_geo:
            action: corahnrin_generator.steps.step_04
        05_social_class:
            action: corahnrin_generator.steps.step_05
        06_age:
            action: corahnrin_generator.steps.step_06
            steps_to_disable_on_change:
                - '07_setbacks'
        07_setbacks:
            action: corahnrin_generator.steps.step_07
        08_ways:
            action: corahnrin_generator.steps.step_08
            steps_to_disable_on_change:
                - '09_traits'
                - '10_orientation'
        09_traits:
            action: corahnrin_generator.steps.step_09
        10_orientation:
            action: corahnrin_generator.steps.step_10
        11_advantages:
            action: corahnrin_generator.steps.step_11
        12_mental_health:
            action: corahnrin_generator.steps.step_12
        13_primary_domains:
            action: corahnrin_generator.steps.step_13
        14_upgrade_domains:
            action: corahnrin_generator.steps.step_14
        15_bonus_domains:
            action: corahnrin_generator.steps.step_15
        16_disciplines:
            action: corahnrin_generator.steps.step_16
        17_combat_arts:
            action: corahnrin_generator.steps.step_17
        18_equipment:
            action: corahnrin_generator.steps.step_18
        19_description:
            action: corahnrin_generator.steps.step_19
        20_finish:
            action: corahnrin_generator.steps.step_20

# CORS management for all APIs
nelmio_cors:
    paths:
        "^/":
            allow_credentials: true
            origin_regex: true
            allow_origin:
                - "^(https?://)?%esteren_domains.api%"
                - "^(https?://)?%esteren_domains.corahnrin%"
                - "^(https?://)?%esteren_domains.esterenmaps%"
                - "^(https?://)?%esteren_domains.backoffice%"
            allow_headers: ["Origin","Accept","Content-Type"]
            allow_methods: ["POST","GET","DELETE","PUT","OPTIONS"]
            max_age: 3600
            hosts:
                - "%esteren_domains.api%"

# Used in EasyAdmin's ckeditor fields
ivory_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
                - { name: "basicstyles", items: [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat" ] }
                - { name: "links", items: [ "Link", "Unlink", "Anchor" ] }
                - { name: "insert", items: [ "Image", "Table", "HorizontalRule", "SpecialChar" ] }
                - { name: "tools", items: [ "Maximize" ] }
                - "/"
                - { name: "paragraph", items: [ "NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Blockquote" ] }
                - { name: "styles", items: [ "Styles", "Format" ] }
                - { name: "document", items: [ "Source", "-" ] }
                - { name: "about", items: [ "About" ] }

# Services declaration
services:

    twig.intl_extension:
        class: Twig_Extensions_Extension_Intl
        tags:
            - name: twig.extension
