imports:
    - { resource: _assets.yml }
    - { resource: _esterenmaps.yml }
    - { resource: _corahn_rin.yml }
    - { resource: _pierstoval.yml }
    - { resource: _easy_admin.yml }

parameters:
    version_code: 0.1
    version_date: 05/01/2015
    locale: fr
    locales: [ fr, en, de, es ]
    locales_regex: fr|en|de|es

doctrine:
    orm:
        default_repository_class: Orbitale\Component\DoctrineTools\BaseEntityRepository
    dbal:
        path: "%database_path%" # For eventual sqlite integration

framework:
    translator:      { fallbacks: %locales% } # Activate translator
    trusted_hosts:
        - "^[a-z]+\%esteren_domains.cookiedomain%$"
    session:
        cookie_domain: %esteren_domains.cookieDomain%
        name:   EsterenPortal
    templating:
        assets_version: %version_code%

# Twig Configuration
twig:
    globals:
        version_code: %version_code%
        version_date: %version_date%
        kernel_root_dir: %kernel.root_dir%
        locales: %locales%
        locales_regex: %locales_regex%
        esteren_domains_corahn_rin: %esteren_domains.corahn_rin%
        esteren_domains_esteren_maps: %esteren_domains.esteren_maps%
        esteren_domains_portal: %esteren_domains.portal%
        esteren_domains_backoffice: %esteren_domains.backoffice%
        esteren_domains_api: %esteren_domains.api%
        esteren_domains_cookieDomain: %esteren_domains.cookieDomain%
    form_themes:
            - 'PierstovalToolsBundle:Form:form_div_layout.html.twig'
            - 'PierstovalToolsBundle:Form:fields.html.twig'
            - 'PierstovalToolsBundle:Form:form_errors.html.twig'

assetic:
    bundles:
        - 'EsterenMapsBundle'
        - 'EsterenPortalBundle'
        - 'CorahnRinBundle'
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        uglifyjs:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        uglifycss:
            node: %node_path%
            node_paths: [ %node_modules_path% ]

# Doctrine Configuration
doctrine:
    orm:
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    UserBundle\Entity\User

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/((%locales_regex%)/)?api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }

# JSON beautifier
jms_serializer:
    visitors:
        json:
            options: 480

# Doctrine extensions
stof_doctrine_extensions:
    default_locale: %locale%
    uploadable:
        default_file_path: %kernel.root_dir%/../web/uploads
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            uploadable: true
            sluggable: true
            timestampable: true
            softdeleteable: true

# Services declaration
services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - 'EsterenMapsBundle'
        - 'EsterenPortalBundle'
        - 'CorahnRinBundle'
        - 'EsterenMapsAdminBundle'
        - 'PierstovalTranslationBundle'
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        uglifyjs:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        uglifycss:
            node: %node_path%
            node_paths: [ %node_modules_path% ]

# CORS management
nelmio_cors:
    paths:
      "^/":
          allow_credentials: true
          origin_regex: true
          allow_origin:
              - ^https?://%esteren_domains.api%
              - ^https?://%esteren_domains.portal%
              - ^https?://%esteren_domains.backoffice%
              - ^https?://%esteren_domains.corahn_rin%
              - ^https?://%esteren_domains.esteren_maps%
          allow_headers: ['Origin','Accept','Content-Type']
          allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
          max_age: 3600
          hosts:
              - "^%esteren_domains.api%$"
              - "^%esteren_domains.portal%$"
              - "^%esteren_domains.backoffice%$"
              - "^%esteren_domains.corahn_rin%$"
              - "^%esteren_domains.esteren_maps%$"
