
assetic:
    assets:
        esteren_general_js:
            inputs:
                - components/bootstrap/js/button.js
                - components/bootstrap/js/collapse.js
                - components/bootstrap/js/dropdown.js
                - components/bootstrap/js/modal.js
                - components/bootstrap/js/tooltip.js
                - components/bootstrap/js/popover.js
                - components/bootstrap/js/transition.js
                - components/bootstrap/js/tab.js
                - @EsterenPortalBundle/Resources/public/js/corahn_rin.js
            filters:
                - ?uglifyjs
            output: js/global.js

        esteren_general_css:
            inputs:
                - components/leaflet/dist/leaflet.css
                - components/leaflet-draw/dist/leaflet.draw.css
                - components/leaflet-sidebar/src/L.Control.Sidebar.css
                - @EsterenPortalBundle/Resources/public/less/_main.less
                - bundles/esterenmaps/css/maps.less
            filters:
                - less
                - cssrewrite
                - ?uglifycss
            output: css/global.css

        esteren_maps_js:
            inputs:
                - components/leaflet/dist/leaflet-src.js
                - components/leaflet-sidebar/leaflet.sidebar-src.js
                - components/leaflet-draw/leaflet.draw-src.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/1_EsterenMap.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/2_LeafletDrawOverrides.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/2_EsterenMap_directions.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/3_EsterenMap_options.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/3_EsterenMap_ActivateLeafletDraw.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addMarker.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addPolyline.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addPolygon.js
                - @EsterenMapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_filters.js
            filters:
                - ?uglifyjs
            output: js/maps_lib.js

        esterenmaps_edit_js:
            inputs:
                - @EsterenMapsBundle/Resources/public/js/map_edit.js
            filters:
                - ?uglifyjs
            output: js/map_edit_more.js
