parameters:
    # Map utilisée pour l'étape 3 du générateur
    step_3_map_id: 1

# Corahn-Rin Api services
corahn_rin_api:
    services:
        maps:           { entity: EsterenMaps\MapsBundle\Entity\Maps }
        markers:        { entity: EsterenMaps\MapsBundle\Entity\Markers }
        markerstypes:   { entity: EsterenMaps\MapsBundle\Entity\MarkersTypes }
        routes:         { entity: EsterenMaps\MapsBundle\Entity\Routes }
        routestypes:    { entity: EsterenMaps\MapsBundle\Entity\RoutesTypes }
        zones:          { entity: EsterenMaps\MapsBundle\Entity\Zones }
