
easy_admin:
    entities:
        ####################
        ## Corahn-Rin
        Armors:
            class: CorahnRin\ModelsBundle\Entity\Armors
        Artifacts:
            class: CorahnRin\ModelsBundle\Entity\Artifacts
        Avantages:
            class: CorahnRin\ModelsBundle\Entity\Avantages
        Books:
            class: CorahnRin\ModelsBundle\Entity\Books
        "Combat Arts":
            class: CorahnRin\ModelsBundle\Entity\CombatArts
        Disciplines:
            class: CorahnRin\ModelsBundle\Entity\Disciplines
        Disorders:
            class: CorahnRin\ModelsBundle\Entity\Disorders
        Flux:
            class: CorahnRin\ModelsBundle\Entity\Flux
        Jobs:
            class: CorahnRin\ModelsBundle\Entity\Jobs
        Miracles:
            class: CorahnRin\ModelsBundle\Entity\Miracles
        Ogham:
            class: CorahnRin\ModelsBundle\Entity\Ogham
        "Ogham types":
            class: CorahnRin\ModelsBundle\Entity\OghamTypes
        Peoples:
            class: CorahnRin\ModelsBundle\Entity\Peoples
        Setbacks:
            class: CorahnRin\ModelsBundle\Entity\Setbacks
        SocialClasses:
            class: CorahnRin\ModelsBundle\Entity\SocialClasses
        Traits:
            class: CorahnRin\ModelsBundle\Entity\Traits
        Weapons:
            class: CorahnRin\ModelsBundle\Entity\Weapons

        ####################
        ## Esteren Maps
        Maps:
            class: EsterenMaps\MapsBundle\Entity\Maps
            list:
                fields: [ id, name, nameSlug, maxZoom, startZoom, startX, startY ]
            form:
                fields: [ name, nameSlug, image, description, maxZoom, startZoom, startX, startY ]
#        Markers:
#            class: EsterenMaps\MapsBundle\Entity\Markers
#            list:
#                fields: [ id, name, latitude, longitude ]
#            form:
#                fields: [ name, description, altitude, latitude, longitude, map, markerType, faction ]
        "Markers types":
            class: EsterenMaps\MapsBundle\Entity\MarkersTypes
            list:
                fields: [ id, name, icon, markers ]
            form:
                fields: [ name, icon, markers ]
#        Routes:
#            class: EsterenMaps\MapsBundle\Entity\Routes
#            list:
#                fields: [ id, name, distance, markerStart, markerEnd ]
#            form:
#                fields: [ name, markerStart, markerEnd ]
        "Routes types":
            class: EsterenMaps\MapsBundle\Entity\RoutesTypes
            list:
                fields: [ id, name, color, routes ]
            form:
                fields: [ name, color ]
#        Zones:
#            class: EsterenMaps\MapsBundle\Entity\Zones
#            list:
#                fields: [ id, name, zoneType, map, faction ]
#            form:
#                fields: [ name, coordinates, map, faction, zoneType ]
        "Zones types":
            class: EsterenMaps\MapsBundle\Entity\ZonesTypes
            list:
                fields: [ id, name, color, parent, zones ]
            form:
                fields: [ name, color, parent ]
