
easy_admin:
    design:
        brand_color: "rgb(88, 88, 216)"
    site_name: Esteren

    entities:

        ####################
        ## Esteren Maps
        "Factions":
            label: "Esteren Maps - Factions"
            class: EsterenMaps\MapsBundle\Entity\Factions
            list:
                fields: [ id, name, description, book ]
            form:
                fields: [ name, description, book ]
        "Maps":
            label: "Esteren Maps - Cartes"
            class: EsterenMaps\MapsBundle\Entity\Maps
            list:
                actions: [ edit, { name: admin_esterenmaps_maps_maps_editInteractive, type: route, label: actions.interactive  } ]
                fields: [ id, name, nameSlug, maxZoom, startZoom, startX, startY ]
            form:
                fields: [ name, nameSlug, image, description, maxZoom, startZoom, startX, startY ]
        "Markers":
            label: "Esteren Maps - Marqueurs"
            class: EsterenMaps\MapsBundle\Entity\Markers
            list:
                fields: [ id, name, latitude, longitude, markerType, { property: webIcon, type: image } ]
            form:
                fields: [ name, description, map, markerType, faction ]
        "MarkersTypes":
            label: "Esteren Maps - Types de marqueurs"
            class: EsterenMaps\MapsBundle\Entity\MarkersTypes
            list:
                fields: [ id, name, { property: webIcon, type: image }, markers ]
            form:
                fields: [ name, icon, markers ]
        "Routes":
            label: "Esteren Maps - Routes"
            class: EsterenMaps\MapsBundle\Entity\Routes
            list:
                fields: [ id, name, distance, description, routeType, markerStart, markerEnd ]
            form:
                fields: [ name, description, routeType, markerStart, markerEnd, faction ]
        "RoutesTypes":
            label: "Esteren Maps - Types de routes"
            class: EsterenMaps\MapsBundle\Entity\RoutesTypes
            list:
                fields: [ id, name, color, routes ]
            form:
                fields: [ name, color ]
        "Zones":
            label: "Esteren Maps - Zones"
            class: EsterenMaps\MapsBundle\Entity\Zones
            list:
                fields: [ id, name, description, zoneType, map, faction ]
            form:
                fields: [ name, description, map, faction, zoneType ]
        "ZonesTypes":
            label: "Esteren Maps - Types de zones"
            class: EsterenMaps\MapsBundle\Entity\ZonesTypes
            list:
                fields: [ id, name, color, parent, zones ]
            form:
                fields: [ name, color, parent ]
        "TransportTypes":
            label: "Esteren Maps - Moyens de transport"
            class: EsterenMaps\MapsBundle\Entity\TransportTypes
            list:
                fields: [ id, name, slug, { property: speed, format: "%.2f" }, description ]
            form:
                fields: [ name, slug, { property: speed, help: "(Km/h)" }, description ]
        "RoutesTransports":
            label: "Esteren Maps - Modificateurs de vitesse (transport)"
            class: EsterenMaps\MapsBundle\Entity\RoutesTransports
            list:
                fields: [ routeType, transportType, { property: percentage, format: %.2f } ]
            form:
                fields: [ routeType, transportType, { property: percentage, format: %.2f, help: "Modificateur de vitesse (en %)" }, positiveRatio ]

        ####################
        ## Pierstoval CMS
        "Pages":
            label: "CMS - Pages"
            class: Pierstoval\Bundle\CmsBundle\Entity\Page
            show:
                fields: [ title, slug, tree, content, metaDescription, metaTitle, metaKeywords, css, js, enabled, homepage, host, createdAt, updatedAt, createdBy, category, parent ]
            list:
                fields: [ id, parent, title, slug, content, category, homepage, host, enabled ]
            form:
                fields: [ title, slug, content, metaDescription, metaTitle, metaKeywords, css, js, category, parent, host, homepage, enabled ]

parameters:
    override: |
        ####################
        ## Corahn-Rin
        Armors:
            class: CorahnRin\CorahnRinBundle\Entity\Armors
            list:
                fields: [ id, name, protection, price, availability ]
            form:
                fields: [ name, protection, price, availability ]
        Artifacts:
            class: CorahnRin\CorahnRinBundle\Entity\Artifacts
            list:
                fields: [ id, price, consumption, consumptionInterval, tank, resistance ]
            form:
                fields: [ price, consumption, consumptionInterval, tank, resistance ]
        Avantages:
            class: CorahnRin\CorahnRinBundle\Entity\Avantages
            list:
                fields: [ id, name, nameFemale, xp, augmentation, isDesv ]
            form:
                fields: [ name, nameFemale, xp, augmentation, bonusDisc, isDesv ]
        Books:
            class: CorahnRin\CorahnRinBundle\Entity\Books
            list:
                fields: [ id, name, description ]
            form:
                fields: [ name, description ]
        "Combat Arts":
            class: CorahnRin\CorahnRinBundle\Entity\CombatArts
            list:
                fields: [ id, name, ranged, melee, xp ]
            form:
                fields: [ name, ranged, melee, xp ]
        Disciplines:
            class: CorahnRin\CorahnRinBundle\Entity\Disciplines
            list:
                fields: [ id, name, rank, book, domains ]
            form:
                fields: [ name, rank, book, domains ]
        Disorders:
            class: CorahnRin\CorahnRinBundle\Entity\Disorders
            list:
                fields: [ id, name, ways, book ]
            form:
                fields: [ name, ways, book ]
        Jobs:
            class: CorahnRin\CorahnRinBundle\Entity\Jobs
            list:
                fields: [ id, name, domainPrimary, domainsSecondary, book ]
            form:
                fields: [ name, domainPrimary, domainsSecondary, book ]
        Miracles:
            class: CorahnRin\CorahnRinBundle\Entity\Miracles
            list:
                fields: [ id, name, isMajor, book ]
            form:
                fields: [ name, isMajor, book ]
        Ogham:
            class: CorahnRin\CorahnRinBundle\Entity\Ogham
            list:
                fields: [ id, name, oghamType, book ]
            form:
                fields: [ name, oghamType, book ]
        "Ogham types":
            class: CorahnRin\CorahnRinBundle\Entity\OghamTypes
            list:
                fields: [ id, name, description ]
            form:
                fields: [ name, description ]
        Peoples:
            class: CorahnRin\CorahnRinBundle\Entity\Peoples
            list:
                fields: [ id, name, description, book ]
            form:
                fields: [ name, description, book ]
        Setbacks:
            class: CorahnRin\CorahnRinBundle\Entity\Setbacks
            list:
                fields: [ id, name, malus, book ]
            form:
                fields: [ name, malus, book ]
        SocialClasses:
            class: CorahnRin\CorahnRinBundle\Entity\SocialClasses
            list:
                fields: [ id, name, description, domains ]
            form:
                fields: [ name, description, domains ]
        Traits:
            class: CorahnRin\CorahnRinBundle\Entity\Traits
            list:
                fields: [ id, name, nameFemale, isQuality, isMajor, way, book ]
            form:
                fields: [ name, nameFemale, isQuality, isMajor, way, book ]
        Weapons:
            class: CorahnRin\CorahnRinBundle\Entity\Weapons
            list:
                fields: [ id, name, damage, price, availability, melee, range ]
            form:
                fields: [ name, damage, price, availability, melee, range ]
