
# Corahn-Rin map tile size
#esterenmaps:
#    tile_size: 168

# Corahn-Rin character sheets source files folder
#corahn_rin_characters:
#    sheets_output: %kernel.root_dir%/cache/character_sheets/
#    sheets_folder: %kernel.root_dir%/../src/CorahnRin/CharactersBundle/SheetsManagers/files/

# Assets
assetic:
    assets:
        esteren_maps_js:
            inputs:
                - '@EsterenMapsBundle/Resources/public/js/leaflet-src.js'
                - '@EsterenMapsBundle/Resources/public/js/leaflet.sidebar-src.js'
                - '@EsterenMapsBundle/Resources/public/js/leaflet.draw-src.js'
                - '@EsterenMapsBundle/Resources/public/js/EsterenMap/1_EsterenMap.js'
                - '@EsterenMapsBundle/Resources/public/js/EsterenMap/2_LeafletDrawOverrides.js'
                - '@EsterenMapsBundle/Resources/public/js/EsterenMap/3_EsterenMap_ActivateLeafletDraw.js'
                - '@EsterenMapsBundle/Resources/public/js/EsterenMap/3_EsterenMap_options.js'
                - '@EsterenMapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addMarker.js'
                - '@EsterenMapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addPolyline.js'
                - '@EsterenMapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_addPolygon.js'
                - '@EsterenMapsBundle/Resources/public/js/EsterenMap/4_EsterenMap_filters.js'
            filters:
                - ?uglifyjs
            output: 'js/maps_lib.js'


# Médias spécifiques à Esteren Maps
sonata_media:
    contexts:
        esteren_maps:
            providers:
                - sonata.media.provider.image
            formats:
                xs:   { width: 50,   quality: 100 }
                s:    { width: 100,  quality: 90 }
                m:    { width: 250,  quality: 80 }
                l:    { width: 500,  quality: 75 }
                xl:   { width: 968,  quality: 70 }
                xxl:  { width: 1366, quality: 70 }
                3xl:  { width: 1900,  quality: 70 }
                4xl:  { width: 2500,  quality: 70 }

        esteren_maps_markers_types:
            providers:
                - sonata.media.provider.image
            formats:
                icon:   { width: 34,  quality: 100 }
                small:  { width: 100, quality: 90 }
                medium: { width: 250, quality: 80 }
                big:    { width: 500, quality: 75 }
                large:  { width: 968, quality: 70 }