
# Api services
pierstoval_api:
    allowed_origins:
        - %esteren_domains.corahn_rin%
        - %esteren_domains.esteren_maps%
        - %esteren_domains.portal%
        - %esteren_domains.backoffice%
        - %esteren_domains.api%
    services:
        maps:           { entity: EsterenMaps\MapsBundle\Entity\Maps }
        markers:        { entity: EsterenMaps\MapsBundle\Entity\Markers }
        markerstypes:   { entity: EsterenMaps\MapsBundle\Entity\MarkersTypes }
        routes:         { entity: EsterenMaps\MapsBundle\Entity\Routes }
        routestypes:    { entity: EsterenMaps\MapsBundle\Entity\RoutesTypes }
        zones:          { entity: EsterenMaps\MapsBundle\Entity\Zones }
        zonestypes:     { entity: EsterenMaps\MapsBundle\Entity\ZonesTypes }
        transports:     { entity: EsterenMaps\MapsBundle\Entity\TransportTypes }

# Gestion de CORS
# Fork de NelmioCorsBundle
pierstoval_cors:
    paths:
      "^/":
          allow_origin:
              - %esteren_domains.api%
              - %esteren_domains.portal%
              - %esteren_domains.backoffice%
              - %esteren_domains.corahn_rin%
              - %esteren_domains.esteren_maps%
          allow_headers: ['Origin', 'X-Requested-With', 'Content-Type', 'Accept', 'Access-Control-Allow-Origin']
          allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
          max_age: 1
          hosts:
              - "^%esteren_domains.api%$"
              - "^%esteren_domains.portal%$"
              - "^%esteren_domains.backoffice%$"
              - "^%esteren_domains.corahn_rin%$"
              - "^%esteren_domains.esteren_maps%$"

orbitale_translation:
    locales: %locales%

pierstoval_cms:
    layouts:
        - { resource: ::base.html.twig, type: front }
