# Configuration for Sonata suite

# Sonata Media
sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    providers:
        image:
            resizer: sonata.media.resizer.simple
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        default:  # the default context is mandatory
            providers:
#                - sonata.media.provider.dailymotion
#                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                icon:   { width: 34,  quality: 100 }
                small:  { width: 100, quality: 90 }
                medium: { width: 250, quality: 80 }
                big:    { width: 500, quality: 75 }
                large:  { width: 968, quality: 70 }
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/
    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false

# Auto mapping for media bundle
doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    SonataMediaBundle: ~
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
