imports:
    - { resource: parameters.yml }
    - { resource: _domains.yml }
    - { resource: security.yml }
    - { resource: _corahnrin.yml }
    - { resource: _easy_admin.yml }
    - { resource: services.yml }

parameters:
    # The version code is always the last version that was put in production
    env(HEROKU_RELEASE_VERSION): 'v50'
    env(HEROKU_RELEASE_CREATED_AT): '2017-07-18T10:53:10Z'

    database_url: '%env(DATABASE_URL)%'
    database_url_legacy: '%env(DATABASE_URL_LEGACY)%'

    version_code: '%env(HEROKU_RELEASE_VERSION)%'
    version_date: '%env(HEROKU_RELEASE_CREATED_AT)%'
    locale: fr
    locales:
        fr: fr
        en: en
    locales_regex: 'fr|en'

    google_tags:
        analytics:   'UA-43812649-5'
        tag_manager: 'GTM-T5PQWF'

framework:
    #esi:             ~
    translator:
        fallbacks: ['%locale%']
    secret:          '%env(SYMFONY_SECRET)%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  '%locale%'
    trusted_hosts:
        - '%env(ESTEREN_DOMAIN)%$'
        - '%env(AGATE_DOMAIN)%$'
        - '%env(VERMINE_DOMAIN)%$'
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:      session.handler.native_file
        save_path:       '%kernel.root_dir%/../var/sessions/%kernel.environment%'
        enabled:         true
        cookie_httponly: true
        name:            AgateApps
        cookie_lifetime: 8640000
        gc_maxlifetime:  86400
    http_method_override: true
    assets:
        version: '%version_code%'
        version_format: '%%s?assetv=%%s'
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        version_code: '%version_code%'
        version_date: '%version_date%'
        locales: '%locales%'
        locales_regex: '%locales_regex%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'form/ckeditor_widget.html.twig'

# Doctrine Configuration
doctrine:
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

        # Override the default repository to get some more good tools
        default_repository_class: Orbitale\Component\DoctrineTools\BaseEntityRepository
        filters:
            # Activate SoftDeleteable for some entities
            # There are some other filters down there
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                url:      '%database_url%'
                charset:  utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
            legacy:
                driver:    pdo_mysql
                url:      '%database_url_legacy%'
                charset:   utf8
                logging:   false
                profiling: false

# Swiftmailer Configuration
swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    host:      '%env(MAILER_HOST)%'
    username:  '%env(MAILER_USER)%'
    password:  '%env(MAILER_PASSWORD)%'
    port:      '%env(MAILER_PORT)%'
    spool:     { type: memory }

# Doctrine extensions
# TODO: Implement Translatable
# TODO: Use KnpDoctrineBehaviors instead, more robust
stof_doctrine_extensions:
    default_locale: '%locale%'
    uploadable:
        default_file_path: '%kernel.root_dir%/../web/uploads'
        mime_type_guesser_class: Stof\DoctrineExtensionsBundle\Uploadable\MimeTypeGuesserAdapter
        default_file_info_class: Stof\DoctrineExtensionsBundle\Uploadable\UploadedFileInfo
    orm:
        default:
            uploadable: true
            sluggable: true
            timestampable: true
            softdeleteable: true

# CORS management for all APIs
nelmio_cors:
    paths:
        '^/':
            allow_credentials: true
            origin_regex: true
            allow_origin:
                - '^(https?://)?%esteren_domains.api%'
                - '^(https?://)?%esteren_domains.corahnrin%'
                - '^(https?://)?%esteren_domains.esterenmaps%'
                - '^(https?://)?%esteren_domains.backoffice%'
            allow_headers: ['Origin','Accept','Content-Type']
            allow_methods: ['POST','GET','DELETE','PUT','OPTIONS']
            max_age: 3600
            hosts:
                - '%esteren_domains.api%'

# Used in EasyAdmin's ckeditor fields
ivory_ck_editor:
    input_sync: true
    default_config: base_config
    jquery: true
    configs:
        base_config:
            language: '%locale%'
            allowedContent: true
            toolbar:
                - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat' ] }
                - { name: 'links',       items: [ 'Link', 'Unlink', 'Anchor' ] }
                - { name: 'insert',      items: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ] }
                - { name: 'tools',       items: [ 'Maximize' ] }
                - '/'
                - { name: 'paragraph',   items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote' ] }
                - { name: 'styles',      items: [ 'Styles', 'Format' ] }
                - { name: 'document',    items: [ 'Source', '-' ] }
                - { name: 'about',       items: [ 'About' ] }

# This allows using the default layout for Pages and Categories
# See: https://github.com/Orbitale/CmsBundle
orbitale_cms:
    page_class:     Esteren\PortalBundle\Entity\Page
    category_class: Esteren\PortalBundle\Entity\Category
    layouts:
        corahnrin:
            resource: '@CorahnRin/layout.html.twig'
            host: '%esteren_domains.corahnrin%'
        maps:
            resource: '@EsterenMaps/layout.html.twig'
            host: '%esteren_domains.esterenmaps%'
        front:
            resource: 'cms_page_layout.html.twig'

# Api services
# TODO: Refactor this and use a better method to generate WS based on entities
# TODO: Implement ApiPlatform
pierstoval_api:
    allowed_origins:
        - '%esteren_domains.esterenmaps%'
        - '%esteren_domains.corahnrin%'
        - '%esteren_domains.backoffice%'
        - '%esteren_domains.api%'
#        - 127.0.0.1 # To add in dev mode if needed

    services:
        maps:           { entity: EsterenMaps\MapsBundle\Entity\Maps }
        markers:        { entity: EsterenMaps\MapsBundle\Entity\Markers }
        markerstypes:   { entity: EsterenMaps\MapsBundle\Entity\MarkersTypes }
        routes:         { entity: EsterenMaps\MapsBundle\Entity\Routes }
        routestypes:    { entity: EsterenMaps\MapsBundle\Entity\RoutesTypes }
        zones:          { entity: EsterenMaps\MapsBundle\Entity\Zones }
        zonestypes:     { entity: EsterenMaps\MapsBundle\Entity\ZonesTypes }
        transports:     { entity: EsterenMaps\MapsBundle\Entity\TransportTypes }

# TODO: remove FOSRest integration or refactor it
# TODO: Implement ApiPlatform
fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/((%locales_regex%)/)?api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
