imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: true

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']

# JSON beautifier in JMS serializer
jms_serializer:
    visitors:
        json:
            # Corresponds to these constants:
            options:
                - JSON_NUMERIC_CHECK
                - JSON_UNESCAPED_SLASHES
                - JSON_UNESCAPED_UNICODE
                - JSON_PRETTY_PRINT
                - JSON_PRESERVE_ZERO_FRACTION

#swiftmailer:
#    delivery_addresses: ['me@example.com']
