imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

# Monolog is overriden because we need to send an e-mail when there is any error.
monolog:
    handlers:

        console:
            type:  console

        # Get ALL error logs and put them to stderr for heroku
        main:
            type:           stream
            path:           'php://stderr'
            level:          info

        # All "error" are sent into another file, including 404 for example
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            path:           '%kernel.logs_dir%/%kernel.environment%.log'
            level:          debug

        ## For any "critical", we send an email
        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        buffered_critical
            include_stacktraces: true
        buffered_critical:
            type:           buffer
            handler:        swift_critical
            include_stacktraces: true
        swift_critical:
            type:           swift_mailer
            from_email:     no-reply@pierstoval.com
            to_email:       pierstoval+esterenprod@gmail.com
            subject:        An Error Occurred!
            level:          debug
            include_stacktraces: true
