imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: _esterenmaps.yml }
    - { resource: _corahn_rin.yml }
    - { resource: _pierstoval.yml }
    - { resource: "@PierstovalTranslationBundle/Resources/config/services.xml" }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
#        cache: apc
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  %locale%
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        # Overrides des formulaires
        resources:
            - 'PierstovalToolsBundle:Form:form_div_layout.html.twig'
            - 'PierstovalToolsBundle:Form:fields.html.twig'
            - 'PierstovalToolsBundle:Form:form_errors.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - 'EsterenMapsBundle'
        - 'EsterenPagesBundle'
        - 'CorahnRinGeneratorBundle'
        - 'PierstovalTranslationBundle'
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [ %node_modules_path% ]
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css: ~
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        #yui_js: ~
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# ------------------------------------------------------------------
# --------------------- Personal configuration ---------------------
# ------------------------------------------------------------------

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    CorahnRin\UsersBundle\Entity\Users
    group:
        group_class: CorahnRin\UsersBundle\Entity\Groups

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
#        view_response_listener: 'force'
#    routing_loader:
#        include_format: false

# JSON beautifier
jms_serializer:
    visitors:
        json:
            options: 480

#sensio_framework_extra:
#    view:    { annotations: true }
#    router:  { annotations: true }

# Doctrine extensions
stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            sluggable: true
            timestampable: true
            softdeleteable: true

# Services declaration
services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

