imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@PierstovalTranslationBundle/Resources/config/services.xml" }

framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
#        cache: apc
    templating:
        engines: ['twig','php']
        #assets_version: SomeVersionScheme
    default_locale:  fr
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'CorahnRinToolsBundle:Form:form_div_layout.html.twig'
            - 'CorahnRinToolsBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
        - 'EsterenMapsBundle'
        - 'CorahnRinCharactersBundle'
        - 'CorahnRinPagesBundle'
        - 'CorahnRinGeneratorBundle'
        - 'PierstovalTranslationBundle'
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
#        yui_css: ~
#            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
#        yui_js: ~
#            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# ------------------------------------------------------------------
# --------------------- Personal configuration ---------------------
# ------------------------------------------------------------------

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    CorahnRin\UsersBundle\Entity\Users

fos_rest:
    param_fetcher_listener: true
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json', 'html'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', '*/*'], fallback_format: ~, prefer_extension: true }
#        view_response_listener: 'force'
#    routing_loader:
#        include_format: false

# JSON beautifier
jms_serializer:
    visitors:
        json:
            options: 480

#sensio_framework_extra:
#    view:    { annotations: true }
#    router:  { annotations: true }

# Doctrine extensions
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

# Services declaration
services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

# Corahn-Rin map tile size
#esterenmaps:
#    tile_size: 168

# Corahn-Rin character sheets source files folder
#corahn_rin_characters:
#    sheets_output: %kernel.root_dir%/cache/character_sheets/
#    sheets_folder: %kernel.root_dir%/../src/CorahnRin/CharactersBundle/Sheets/files/

# Corahn-Rin Api services
corahn_rin_api:
    services:
        maps:           { entity: EsterenMaps\MapsBundle\Entity\Maps }
        markers:        { entity: EsterenMaps\MapsBundle\Entity\Markers }
        markerstypes:   { entity: EsterenMaps\MapsBundle\Entity\MarkersTypes }
        routes:         { entity: EsterenMaps\MapsBundle\Entity\Routes }
        routestypes:    { entity: EsterenMaps\MapsBundle\Entity\RoutesTypes }
        zones:          { entity: EsterenMaps\MapsBundle\Entity\Zones }
