imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine config for Esteren app: we need a Sqlite database
doctrine:
    dbal:
        driver:   pdo_sqlite
        dbname:   db_test.db
        charset:  UTF8
        path:     '%kernel.root_dir%/../build/database_test.db'

# Force these domain names to be used in the tests
parameters:
    esteren_domains.corahnrin:      corahnrin.esteren.dev
    esteren_domains.esteren_maps:   maps.esteren.dev
    esteren_domains.portal:         www.esteren.dev
    esteren_domains.backoffice:     back.esteren.dev
    esteren_domains.api:            api.esteren.dev
    esteren_domains.games:          games.esteren.dev
    esteren_domains.cookie_domain:  .esteren.dev
