imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine config for Esteren app: we need a Sqlite database
doctrine:
    dbal:
        connections:
            default:
                driver:   pdo_sqlite
                dbname:   db_test.db
                charset:  UTF8
                path:     '%kernel.root_dir%/../build/database_test.db'
                charset:  UTF8
            legacy:
                driver:   pdo_sqlite
                dbname:   db_test_legacy.db
                charset:  UTF8
                path:     '%kernel.root_dir%/../build/database_test_legacy.db'
                charset:  UTF8

# Force these domain names to be used in the tests
parameters:
    esteren_domain: esteren.dev
