imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: fr }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:
        enable_annotations: true
        cache: apc
    templating:
        engines: ['twig','php']
        #assets_version: SomeVersionScheme
    default_locale:  fr
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'CorahnRinToolsBundle:Form:form_div_layout.html.twig'
            - 'CorahnRinToolsBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['CorahnRinMapsBundle','CorahnRinCharactersBundle','CorahnRinTranslateBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver:     orm
    firewall_name: main
    user_class:    CorahnRin\UsersBundle\Entity\Users

# Doctrine extensions
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
    corahn_rin_translate:
        class: CorahnRin\TranslateBundle\Classes\Translator
        arguments:
            locale: %kernel.default_locale%
            translation_output: "%kernel.root_dir%/Resources/Translations/"
            langs: fr,en,de
    MapTileCommandService:
        class: CorahnRin\MapsBundle\Command\MapTileCommand
        calls:
            - [setContainer, ["@service_container"] ]

corahn_rin_maps:
    tile_size: 168
