imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
    trusted_hosts:
        - localhost # Mostly for behat

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Doctrine config for Esteren app: we need a Sqlite database
doctrine:
    dbal:
        connections:
            default:
                driver: pdo_sqlite
                path:   '%kernel.root_dir%/../build/database_test.db'
            legacy:
                driver: pdo_sqlite
                path:   '%kernel.root_dir%/../build/database_test_legacy.db'
