corahn_rin_admin:
    resource: "@CorahnRinAdminBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.corahn_rin%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# Corahn-Rin relative routing
corahn_rin_generator:
    resource: "@CorahnRinGeneratorBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.corahn_rin%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

esteren_pages:
    resource: "@EsterenPagesBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.portal%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

corahn_rin_characters:
    resource: "@CorahnRinCharactersBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.corahn_rin%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# Esteren Maps relative routing
esterenmaps:
    resource: "@EsterenMapsBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.esteren_maps%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# Pierstoval relative routing
pierstoval_tools:
    resource: "@PierstovalToolsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_translation:
    resource: "@PierstovalTranslationBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_api:
    resource: "@PierstovalApiBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_admin:
    resource: "@PierstovalAdminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# FOS relative Routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /{_locale}/group
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

#-----------------------------------
# Sonata relative Routing
sonata_cache_cache:
    resource:    "@SonataCacheBundle/Resources/config/routing/cache.xml"
    prefix:      /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

sonata_page_exceptions:
    resource:    "@SonataPageBundle/Resources/config/routing/exceptions.xml"
    prefix:      /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

sonata_page_cache:
    resource:    "@SonataPageBundle/Resources/config/routing/cache.xml"
    prefix:      /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix:   /{_locale}/admin/
    host:     %esteren_domains.backoffice%

_sonata_admin:
    resource:    .
    type:        sonata_admin
    prefix:      /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:        %esteren_domains.backoffice%

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix:      /{_locale}/admin
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:        %esteren_domains.backoffice%

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
    prefix:     /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:       %esteren_domains.backoffice%

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix:     /{_locale}/admin/resetting
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:       %esteren_domains.backoffice%

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix:     /{_locale}/admin/profile
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:       %esteren_domains.backoffice%

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix:     /{_locale}/admin/register
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:       %esteren_domains.backoffice%

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix:     /{_locale}/admin/profile
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:       %esteren_domains.backoffice%

sonata_admin_security:
    resource:    "@ApplicationSonataAdminBundle/Controller/"
    type:        annotation
    prefix:      /
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:        %esteren_domains.backoffice%