orbitale_cms_page:
    resource: "@OrbitaleCmsBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /{_locale}/page/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

orbitale_cms_category:
    resource: "@OrbitaleCmsBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /{_locale}/category/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
