
contact:
    resource: "@EsterenPortalBundle/Controller/ContactController.php"
    type:     annotation

orbitale_cms_category:
    resource: "@OrbitaleCmsBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /category/

portal:
    resource: "@OrbitaleCmsBundle/Controller/PageController.php"
    type:     annotation
    prefix:   /
    defaults:
        domainName: '%esteren_domains.portal%'
        slugs: ""
    requirements:
        domainName: "^(?:%esteren_domains.portal%|%esteren_domains.games%|%esteren_domains.corahnrin%)$"
