
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

esterenmaps:
    resource: "@EsterenMapsBundle/Controller/"
    type:     annotation
    prefix: "/{_locale}/"
    defaults: { _locale: "%locale%" }
    requirements: { _locale: "^(?:%locales_regex%)$" }

esterenmaps_api:
    resource: "@EsterenMapsApiBundle/Controller/"
    type:     annotation
    prefix: "/{_locale}/"
    defaults: { _locale: "%locale%" }
    requirements: { _locale: "^(?:%locales_regex%)$" }

# Hack to simulate FOSUserBundle in some parts of the app
fos_user_security_login:
    path: /login
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /
        permanent: true

#-----------------------------------
# Pierstoval relative routing
pierstoval_tools:
    resource: "@PierstovalToolsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    host:     %esteren_domains.portal%
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_api:
    resource: "@PierstovalApiBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.api%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
