imports:
    resource: routing_sonata.yml

#-----------------------------------
# Corahn-Rin relative routing
corahn_rin_generator:
    resource: "@CorahnRinGeneratorBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.corahn_rin%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

corahn_rin_admin:
    resource: "@CorahnRinAdminBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.corahn_rin%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

corahn_rin_characters:
    resource: "@CorahnRinCharactersBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.corahn_rin%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

esteren_portal:
    resource: "@EsterenPortalBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.portal%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# Esteren Maps relative routing
esterenmaps:
    resource: "@EsterenMapsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

esterenmaps_api:
    resource: "@EsterenMapsApiBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

esterenmaps_admin:
    resource:    "@EsterenMapsAdminBundle/Controller/"
    type:        annotation
    prefix:      /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:        %esteren_domains.backoffice%

#-----------------------------------
# Pierstoval relative routing
pierstoval_tools:
    resource: "@PierstovalToolsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    host:     %esteren_domains.portal%
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_api:
    resource: "@PierstovalApiBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.api%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_admin:
    resource: "@PierstovalAdminBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.portal%
    prefix:   /{_locale}/admin/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# FOS relative Routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.portal%

#-----------------------------------
# Admin relative Routing
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/admin/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.backoffice%
