sonata:      { resource: routing_sonata.yml }
fos:         { resource: routing_fos.yml }
orbitale:    { resource: routing_orbitale.yml }
corahnrin:   { resource: routing_corahnrin.yml }
esterenmaps: { resource: routing_esterenmaps.yml }

esteren_portal:
    resource: "@EsterenPortalBundle/Controller/"
    type:     annotation

#-----------------------------------
# Pierstoval relative routing
pierstoval_tools:
    resource: "@PierstovalToolsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    host:     %esteren_domains.portal%
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_api:
    resource: "@PierstovalApiBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.api%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# Admin relative Routing
application_admin:
    resource: "@ApplicationAdminBundle/Controller"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.backoffice%
