corahn_rin_generator:
    resource: "@CorahnRinBundle/Controller/CharacterViewController.php"
    type:     annotation
    host:     %esteren_domains.corahn_rin%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
