
# Root comes after all portals and redirects to default locale permanently
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: '/%locale%/'
        permanent: true
    schemes: [https]

main:
    resource: routing/_main.yml
    schemes: [https]
    prefix: '/{_locale}/'
    defaults:
        _locale: '%locale%'
    requirements:
        _locale: '^(?:%locales_regex%)$'
