esterenmaps:
    resource: "@EsterenMapsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

esterenmaps_api:
    resource: "@EsterenMapsApiBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

esterenmaps_admin:
    resource:    "@EsterenMapsAdminBundle/Controller/"
    type:        annotation
    prefix:      /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host:        %esteren_domains.backoffice%
