fos:         { resource: "routing__fos.yml", prefix: "/{_locale}/", defaults: { _locale: "%locale%" }, requirements: { _locale: "^(%locales_regex%)$" }  }
orbitale:    { resource: "routing__orbitale.yml", prefix: "/{_locale}/", defaults: { _locale: "%locale%" }, requirements: { _locale: "^(%locales_regex%)$" }  }
corahnrin:   { resource: "routing__corahnrin.yml", prefix: "/{_locale}/", defaults: { _locale: "%locale%" }, requirements: { _locale: "^(%locales_regex%)$" }  }
esterenmaps: { resource: "routing__esterenmaps.yml", prefix: "/{_locale}/", defaults: { _locale: "%locale%" }, requirements: { _locale: "^(%locales_regex%)$" }  }

esteren_portal:
    resource: "@EsterenPortalBundle/Controller/"
    type:     annotation
    prefix:   /

#-----------------------------------
# Pierstoval relative routing
pierstoval_tools:
    resource: "@PierstovalToolsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    host:     %esteren_domains.portal%
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_api:
    resource: "@PierstovalApiBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.api%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# Admin relative Routing
application_admin:
    resource: "@AdminBundle/Controller"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.backoffice%
