# Be careful to manually prefix the local to all your new routes.

# First we load the different other config files with the same configuration
fos:         { resource: "routing__fos.yml",         prefix: "/{_locale}/", defaults: { _locale: "%locale%" }, requirements: { _locale: "^(?:%locales_regex%)$" } }
corahnrin:   { resource: "routing__corahnrin.yml",   prefix: "/{_locale}/", defaults: { _locale: "%locale%" }, requirements: { _locale: "^(?:%locales_regex%)$" } }
esterenmaps: { resource: "routing__esterenmaps.yml", prefix: "/{_locale}/", defaults: { _locale: "%locale%" }, requirements: { _locale: "^(?:%locales_regex%)$" } }

# Root comes after all portals and redirects to default locale permanently
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

#-----------------------------------
# Pierstoval bundles relative routing
pierstoval_tools:
    resource: "@PierstovalToolsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    host:     %esteren_domains.portal%
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

pierstoval_api:
    resource: "@PierstovalApiBundle/Controller/"
    type:     annotation
    host:     %esteren_domains.api%
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$

#-----------------------------------
# Admin relative Routing
application_admin:
    resource: "@AdminBundle/Controller"
    type:     annotation
    prefix:   /{_locale}/
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.backoffice%

lexik_translation_admin:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/translations
    defaults:
         _locale: %locale%
    requirements:
        _locale: ^(%locales_regex%)$
    host: %esteren_domains.backoffice%

#-----------------------------------
# Portal routing. MUST be at the end, because it's an OrbitaleCms routing,
#   and therefore has many dynamic urls that will come as "fallback" to any other
#   application routing.
portal: { resource: "routing__portal.yml", prefix: "/{_locale}/", defaults: { _locale: "%locale%" }, requirements: { _locale: "^(?:%locales_regex%)$" } }
