
#-----------------------------------
# Sonata relative Routing
#gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    host:     %esteren_domains.portal%
#    prefix:   /media/gallery/

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    host:     %esteren_domains.portal%
    prefix:   /media/
