corahn_rin_admin:
    resource: "@CorahnRinAdminBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/


#-----------------------------------
# Corahn-Rin relative routing
corahn_rin_generator:
    resource: "@CorahnRinGeneratorBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

esteren_pages:
    resource: "@EsterenPagesBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

corahn_rin_characters:
    resource: "@CorahnRinCharactersBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

#-----------------------------------
# Esteren Maps relative routing
esterenmaps:
    resource: "@EsterenMapsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

#-----------------------------------
# Pierstoval relative routing
pierstoval_tools:
    resource: "@PierstovalToolsBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

pierstoval_translation:
    resource: "@PierstovalTranslationBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

pierstoval_api:
    resource: "@PierstovalApiBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/

pierstoval_admin:
    resource: "@PierstovalAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin/

#-----------------------------------
# FOS relative Routing
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

#-----------------------------------
# Sonata relative Routing
sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /
sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /
sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
    prefix: /