
portal:
    host: "{domainName}"
    path: /
    defaults:
        _controller: OrbitaleCmsBundle:Page:index
        domainName: %esteren_domains.portal%
    requirements:
        domainName: "^(?:%esteren_domains.portal%|%esteren_domains.games%|%esteren_domains.corahn_rin%)$"

