
portal:
    host: %esteren_domains.portal%
    path: /
    defaults:
        _controller: OrbitaleCmsBundle:Page:index

portal_games:
    host: %esteren_domains.games%
    path: /
    defaults:
        _controller: OrbitaleCmsBundle:Page:index
