esterenmaps:
    resource: "@EsterenMapsBundle/Controller/"
    type:     annotation

esterenmaps_api:
    resource: "@EsterenMapsApiBundle/Controller/"
    type:     annotation

esterenmaps_admin:
    resource:    "@EsterenMapsAdminBundle/Controller/"
    type:        annotation
    host:        %esteren_domains.backoffice%
