security:
    acl:
        connection: default

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        # Managers de contenu (utile pour les newsletter par exemple)
        ROLE_MANAGER:                   ROLE_USER

        # Maps
        ROLE_ADMIN_MAPS:                ROLE_MANAGER
        ROLE_ADMIN_MAPS_SUPER:          ROLE_ADMIN_MAPS

        # Generator
        ROLE_ADMIN_GENERATOR:           ROLE_MANAGER
        ROLE_ADMIN_GENERATOR_SUPER:     ROLE_ADMIN_GENERATOR

        # Translator
        ROLE_ADMIN_TRANSLATOR:          ROLE_MANAGER

        # Site manager
        ROLE_ADMIN_MANAGE_SITE:         ROLE_MANAGER
        ROLE_ADMIN_MANAGE_SITE_SUPER:   ROLE_ADMIN_MANAGE_SITE

        # Admins
        ROLE_ADMIN:
            - ROLE_MANAGER
            - ROLE_ADMIN_GENERATOR
            - ROLE_ADMIN_MAPS
            - ROLE_ADMIN_MANAGE_SITE
            - ROLE_ADMIN_TRANSLATOR
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ADMIN_GENERATOR_SUPER
            - ROLE_ADMIN_MAPS_SUPER
            - ROLE_ADMIN_MANAGE_SITE_SUPER
            - ROLE_ALLOWED_TO_SWITCH
            - SONATA
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT

    providers:
        main:
            id: fos_user.user_provider.username
        fos_userbundle:
            id: fos_user.user_provider.username
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Classic front-office + specific user content
        main:
            pattern:            ^/
            anonymous:          true
            host:               %esteren_domains.portal%|%esteren_domains.corahn_rin%|%esteren_domains.esteren_maps%
            context:            frontoffice
            remember_me:
                key:            %secret%
                path:           /
            form_login:
                provider:       main
                login_path:     fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                failure_path:   null
                use_referer:    true
            logout:
                path:           fos_user_security_logout
                target:         /

        # Sonata Backoffice
        admin:
            pattern:            ^/
            host:               %esteren_domains.backoffice%
            anonymous:          false
            context:            backoffice
            remember_me:        false
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_admin_security_login
                use_forward:    false
                check_path:     sonata_admin_security_check
                failure_path:   null
                use_referer:    true
            logout:
                path:           sonata_admin_security_logout
                target:         http://%esteren_domains.portal%/%locale%/

    access_control:
        - { path: ^/(%locales_regex%)/register,           roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/(%locales_regex%)/resetting,          roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/(%locales_regex%)/maps,               roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/(%locales_regex%)/api/maps,           roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/(%locales_regex%)/profile,            roles: [ROLE_USER] }
        - { path: ^/(%locales_regex%)/characters,         roles: [ROLE_USER] }
        - { path: ^/(%locales_regex%)/,                   roles: [SONATA_ADMIN, ROLE_USER],     host: %esteren_domains.backoffice }
