# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#encoding-the-user-s-password
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/security.html#hierarchical-roles
    role_hierarchy:

        # Anyone who is a backer from Kickstarter or Ulule.
        ROLE_BACKER: ROLE_USER

        # A user that can view the map is automatically a user.
        ROLE_MAPS_VIEW: ROLE_USER

        # Backers "Travels" reedition
        ROLE_BACKER_TRAVELS:
            - ROLE_BACKER
            - ROLE_MAPS_VIEW

        # Content managers (access to backend)
        ROLE_MANAGER:                   ROLE_USER

        # Maps
        ROLE_ADMIN_MAPS:                ROLE_MANAGER

        # Character Generator
        ROLE_ADMIN_GENERATOR:           ROLE_MANAGER

        # Translator
        ROLE_ADMIN_TRANSLATOR:          ROLE_MANAGER

        # Site manager (CMS)
        ROLE_ADMIN_MANAGE_SITE:         ROLE_MANAGER

        # Admins
        ROLE_ADMIN:
            - ROLE_MANAGER
            - ROLE_ADMIN_GENERATOR
            - ROLE_ADMIN_MAPS
            - ROLE_ADMIN_MANAGE_SITE
            - ROLE_ADMIN_TRANSLATOR
        ROLE_SUPER_ADMIN:
            - ROLE_BACKER_TRAVELS
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_user:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
        # http://symfony.com/doc/current/security/form_login_setup.html
        main:
            pattern:            ^/
            anonymous:          ~
            remember_me:
                secret:         "%secret%"
                path:           /
                name:           EsterenRememberMe
                domain:         "%esteren_domains.cookie_domain%"
            form_login:
                csrf_token_generator: security.csrf.token_manager
                provider:       fos_user
                login_path:     fos_user_security_login
                use_forward:    true
                check_path:     fos_user_security_check
                use_referer:    true
            logout:
                invalidate_session: false
                path:           fos_user_security_logout
                target:         root

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/security.html#security-book-access-control-matching-options
    access_control:
        - { path: "^/(?:%locales_regex%)/login$",     role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/(?:%locales_regex%)/register",   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/(?:%locales_regex%)/resetting",  role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/(?:%locales_regex%)/profile",    roles: [ROLE_USER] }
        - { path: "^/(?:%locales_regex%)/characters", roles: [ROLE_USER] }
        - { path: "^/",                               host: "%esteren_domains.backoffice%",   role: ROLE_MANAGER }
        - { path: "^/",                               host: "%esteren_domains.api%",          role: ROLE_MANAGER, methods: [POST, PUT, DELETE] }
        - { path: "^/",                               host: "%esteren_domains.esterenmaps%",  role: ROLE_MAPS_VIEW }
