security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        # Managers de contenu (utile pour les newsletter par exemple)
        ROLE_MANAGER:                   ROLE_USER

        # Maps
        ROLE_ADMIN_MAPS:                ROLE_MANAGER
        ROLE_ADMIN_MAPS_SUPER:          ROLE_ADMIN_MAPS

        # Generator
        ROLE_ADMIN_GENERATOR:           ROLE_MANAGER
        ROLE_ADMIN_GENERATOR_SUPER:     ROLE_ADMIN_GENERATOR

        # Translator
        ROLE_ADMIN_TRANSLATOR:          ROLE_MANAGER

        # Site manager
        ROLE_ADMIN_MANAGE_SITE:         ROLE_MANAGER
        ROLE_ADMIN_MANAGE_SITE_SUPER:   ROLE_ADMIN_MANAGE_SITE

        # Admins
        ROLE_ADMIN:
            - ROLE_MANAGER
            - ROLE_ADMIN_GENERATOR
            - ROLE_ADMIN_MAPS
            - ROLE_ADMIN_MANAGE_SITE
            - ROLE_ADMIN_TRANSLATOR
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ADMIN_GENERATOR_SUPER
            - ROLE_ADMIN_MAPS_SUPER
            - ROLE_ADMIN_MANAGE_SITE_SUPER
            - ROLE_ALLOWED_TO_SWITCH

    providers:
        main:
            id: fos_user.user_provider.username
        fos_userbundle:
            id: fos_user.user_provider.username
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                check_path:     fos_user_security_check
                csrf_provider:  form.csrf_provider
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret%

    access_control:
        - { path: ^(/(fr|de|en|es)?)?/login$,             role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(fr|de|en|es)?)?/register,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(fr|de|en|es)?)?/resetting,          role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(fr|de|en|es)?)?/maps,               role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(fr|de|en|es)?)?/api/maps,           role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^(/(fr|de|en|es)?)?/,                   role: ROLE_USER }
        - { path: ^(/(fr|de|en|es)?)?/profile,            role: ROLE_USER }
        - { path: ^(/(fr|de|en|es)?)?/admin/maps,         role: ROLE_ADMIN_MAPS }
        - { path: ^(/(fr|de|en|es)?)?/admin/generator,    role: ROLE_ADMIN_GENERATOR }
        - { path: ^(/(fr|de|en|es)?)?/admin/manage_site,  role: ROLE_ADMIN }
        - { path: ^(/(fr|de|en|es)?)?/admin/super,        role: ROLE_SUPER_ADMIN }
