# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:

        ROLE_BACKER: ROLE_USER

        # Backers "Travels" reedition
        ROLE_BACKER_TRAVELS:
            - ROLE_BACKER
            - ROLE_MAPS_VIEW

        # Managers de contenu (accès à l'administration)
        ROLE_MANAGER:                   ROLE_USER

        # Maps
        ROLE_ADMIN_MAPS:                ROLE_MANAGER
        ROLE_ADMIN_MAPS_SUPER:          ROLE_ADMIN_MAPS

        # Generator
        ROLE_ADMIN_GENERATOR:           ROLE_MANAGER
        ROLE_ADMIN_GENERATOR_SUPER:     ROLE_ADMIN_GENERATOR

        # Translator
        ROLE_ADMIN_TRANSLATOR:          ROLE_MANAGER

        # Site manager
        ROLE_ADMIN_MANAGE_SITE:         ROLE_MANAGER
        ROLE_ADMIN_MANAGE_SITE_SUPER:   ROLE_ADMIN_MANAGE_SITE

        # Admins
        ROLE_ADMIN:
            - ROLE_MANAGER
            - ROLE_ADMIN_GENERATOR
            - ROLE_ADMIN_MAPS
            - ROLE_ADMIN_MANAGE_SITE
            - ROLE_ADMIN_TRANSLATOR
        ROLE_SUPER_ADMIN:
            - ROLE_BACKER_TRAVELS
            - ROLE_ADMIN
            - ROLE_ADMIN_GENERATOR_SUPER
            - ROLE_ADMIN_MAPS_SUPER
            - ROLE_ADMIN_MANAGE_SITE_SUPER
            - ROLE_ALLOWED_TO_SWITCH

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_user:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:            ^/
            anonymous:          ~
            remember_me:
                secret:         "%secret%"
                path:           /
                name:           EsterenRememberMe
                domain:         "%%esteren_domains.cookiedomain%"
            form_login:
                provider:       fos_user
                login_path:     fos_user_security_login
                csrf_provider:  form.csrf_provider
                use_forward:    true
                check_path:     fos_user_security_check
                use_referer:    true
            logout:
                path:           fos_user_security_logout
                target:         root

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        - { path: "^/(?:%locales_regex%)/profile",    roles: [ROLE_USER] }
        - { path: "^/(?:%locales_regex%)/characters", roles: [ROLE_USER] }
        - { path: "^/",                               host: "%esteren_domains.backoffice%",   roles: ROLE_MANAGER }
        - { path: "^/",                               host: "%esteren_domains.api%",          roles: ROLE_MANAGER, methods: [POST, PUT, DELETE] }
        - { path: "^/",                               host: "%esteren_domains.esteren_maps%", roles: ROLE_MAPS_VIEW }
