# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        # Managers de contenu (utile pour les newsletter par exemple)
        ROLE_MANAGER:                   ROLE_USER

        # Maps
        ROLE_ADMIN_MAPS:                ROLE_MANAGER
        ROLE_ADMIN_MAPS_SUPER:          ROLE_ADMIN_MAPS

        # Generator
        ROLE_ADMIN_GENERATOR:           ROLE_MANAGER
        ROLE_ADMIN_GENERATOR_SUPER:     ROLE_ADMIN_GENERATOR

        # Translator
        ROLE_ADMIN_TRANSLATOR:          ROLE_MANAGER

        # Site manager
        ROLE_ADMIN_MANAGE_SITE:         ROLE_MANAGER
        ROLE_ADMIN_MANAGE_SITE_SUPER:   ROLE_ADMIN_MANAGE_SITE

        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  # if you are using acl then this line must be commented
            - ROLE_SONATA_PAGE_ADMIN_BLOCK_EDIT

        ROLE_SONATA_ADMIN:
            - ROLE_USER

        # Admins
        ROLE_ADMIN:
            - ROLE_MANAGER
            - ROLE_ADMIN_GENERATOR
            - ROLE_ADMIN_MAPS
            - ROLE_ADMIN_MANAGE_SITE
            - ROLE_ADMIN_TRANSLATOR
            - ROLE_SONATA_ADMIN
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ADMIN_GENERATOR_SUPER
            - ROLE_ADMIN_MAPS_SUPER
            - ROLE_ADMIN_MANAGE_SITE_SUPER
            - ROLE_ALLOWED_TO_SWITCH

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_user:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Sonata Backoffice
        admin:
            pattern:            ^/
            host:               %esteren_domains.backoffice%
            anonymous:          true
            context:            backoffice
            remember_me:        false
            form_login:
                provider:       fos_user
                login_path:     sonata_user_admin_security_login
                use_forward:    false
                check_path:     sonata_user_admin_security_check
                failure_path:   null
                use_referer:    false
                default_target_path: sonata_admin_dashboard
                always_use_default_target_path: true
            logout:
                path:           sonata_user_admin_security_logout
                target:         root

        # Classic front-office + specific user content
        main:
            pattern:            ^/
            anonymous:          true
            host:               (%esteren_domains.portal%|%esteren_domains.corahn_rin%|%esteren_domains.esteren_maps%)
            context:            frontoffice
            remember_me:
                key:            %secret%
                path:           /
            form_login:
                provider:       fos_user
                login_path:     fos_user_security_login
                use_forward:    false
                check_path:     fos_user_security_check
                failure_path:   null
                use_referer:    true
            logout:
                path:           fos_user_security_logout
                target:         root

    # with these settings you can restrict or allow access for different parts
    # of your application based on roles, ip, host or methods
    # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
    access_control:
        - { path: ^/(%locales_regex%)/,                         roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/(%locales_regex%)/profile,                  roles: [ROLE_USER] }
        - { path: ^/(%locales_regex%)/characters,               roles: [ROLE_USER] }
        - { path: ^/(%locales_regex%)/admin/,                   host: %esteren_domains.backoffice%, roles: [ROLE_SONATA_ADMIN] }
