version: 2

jobs:
    build:
        docker:
            # Docker build here:
            # https://hub.docker.com/r/pierstoval/studio-agate-portal/
            # https://github.com/StudioAgate/DockerPortalApp
            - image: pierstoval/studio-agate-portal

        working_directory: ~/app

        environment:
            NODE_ENV:      production
            SYMFONY_ENV:   test
            SYMFONY_DEBUG: 1
            RECREATE_DB:   1

        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-cache-{{ checksum "composer.lock" }}
                    - composer-cache-{{ .Branch }}
                    - yarn-cache-{{ checksum "yarn.lock" }}
                    - yarn-cache-{{ .Branch }}

            - run:
                name: 'Show config'
                command: |
                    pwd
                    php --ini
                    composer config -l

            - run:
                name: 'Prepare environment'
                command: |
                    echo "date.timezone = Europe/Paris" > /usr/local/etc/php/conf.d/custom.ini
                    echo "short_open_tag = off" >> /usr/local/etc/php/conf.d/custom.ini
                    echo "apcu.enable_cli = 1" >> /usr/local/etc/php/conf.d/custom.ini

                    cp tests/ci/.env .env
                    cp tests/ci/phpunit.xml ./phpunit.xml

            - run:
               name: 'Install Project Dependencies'
               command: |
                    composer install --no-interaction --no-suggest --ignore-platform-reqs --no-progress
                    yarn install

            - run:
               name: 'Execute node tests'
               command: |
                    yarn gulp test

            - run:
               name: 'Execute Linting tests'
               command: |
                    php bin/console security:check
                    php bin/console lint:twig templates src
                    php bin/console lint:yaml config
                    php bin/console lint:yaml src

            - run:
               name: 'Execute PHPUnit tests'
               command: |
                    vendor/bin/phpunit

            - save_cache:
                key: composer-cache-{{ checksum "composer.lock" }}
                paths:
                    - ~/.composer/cache

            - save_cache:
                key: composer-cache-{{ .Branch }}
                paths:
                    - ~/.composer/cache

            - save_cache:
                key: yarn-cache-{{ checksum "yarn.lock" }}
                paths:
                    - node_modules

            - save_cache:
                key: yarn-cache-{{ .Branch }}
                paths:
                    - node_modules
