version: 2

jobs:
    php:
        docker:
            # Docker build here:
            # https://hub.docker.com/r/pierstoval/studio-agate-portal/
            # https://github.com/StudioAgate/DockerPortalApp
            - image: circleci/php:7.2-cli

        working_directory: /srv

        environment:
            SYMFONY_ENV:   test
            SYMFONY_DEBUG: 1
            RECREATE_DB:   1

        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-cache-{{ checksum "composer.lock" }}

            - restore_cache:
                keys:
                    - npm-cache-{{ checksum "package-lock.json" }}

            - setup_remote_docker

            - run:
               name: 'Install Project Dependencies'
               command: |
                   make install-php

            - run:
               name: 'Execute PHP tests'
               command: |
                   make php-tests

            - save_cache:
                key: composer-cache-{{ checksum "composer.lock" }}
                paths:
                    - ~/.composer/cache

            - save_cache:
                key: npm-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ~/.npm

    node:
        docker:
            - image: node:10

        working_directory: /srv

        environment:
            NODE_ENV: production

        steps:
            - checkout

            - restore_cache:
                keys:
                    - npm-cache-{{ checksum "package-lock.json" }}

            - run:
                name: 'Show config'
                command: |
                    pwd
                    env
                    node --version
                    npm --version

            - run:
               name: 'Install Project Dependencies'
               command: |
                    npm install

            - run:
               name: 'Execute node tests'
               command: |
                    npm run-script test --verbose -LLLL

            - save_cache:
                key: npm-cache-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules

workflows:
    version: 2
    ci_suite:
        jobs:
            - php
            - node
