doctrine_cache:
    providers:
        metadata_cache:
            php_file:
                extension: cache
                directory: '%kernel.cache_dir%/doctrine/metadata/'
        result_cache:
            php_file:
                extension: cache
                directory: '%kernel.cache_dir%/doctrine/result/'
        query_cache:
            php_file:
                extension: cache
                directory: '%kernel.cache_dir%/doctrine/query/'
