services:
    _defaults:
        autoconfigure: true

    Agate\DataFixtures\:
        resource: ../../../src/Agate/DataFixtures/

    CorahnRin\DataFixtures\:
        resource: ../../../src/CorahnRin/DataFixtures/

    Esteren\DataFixtures\:
        resource: ../../../src/Esteren/DataFixtures/

    EsterenMaps\DataFixtures\:
        resource: ../../../src/EsterenMaps/DataFixtures/
