oneup_flysystem:
    adapters:
        assets_adapter:
            awss3v3:
                client: app.s3
                bucket: '%env(AWS_BUCKET)%'
                prefix: assets

services:
    app.s3:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest'
                region: '%env(AWS_REGION)%'
                credentials:
                    key: '%env(AWS_KEY)%'
                    secret: '%env(AWS_SECRET)%'
