parameters:
    aws_region: '%env(AWS_REGION)%'
    aws_bucket: '%env(AWS_BUCKET)%'
    aws_key: '%env(AWS_KEY)%'
    aws_secret: '%env(AWS_SECRET)%'

oneup_flysystem:
    adapters:
        assets_adapter:
            awss3v3:
                client: app.s3
                bucket: '%aws_bucket%'
                prefix: assets

services:
    app.s3:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest'
                region: '%aws_region%'
                credentials:
                    key: '%aws_key%'
                    secret: '%aws_secret%'
