services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $sheetsFolder: '%kernel.project_dir%/src/CorahnRin/CorahnRinBundle/Resources/pdf_sources'

    # TODO: remove this when updating CharacterManagerBundle
    Pierstoval\Bundle\CharacterManagerBundle\Resolver\StepActionResolver: '@pierstoval.character_manager.step_action_resolver'

    CorahnRin\CorahnRinBundle\:
        resource: '../../{Repository,GeneratorTools,SheetsManagers}'
