services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    CorahnRin\CorahnRinBundle\Repository:
        resource: '../../{Repository}'
        public: true

    CorahnRin\CorahnRinBundle\:
        resource: '../../{GeneratorTools}'

    CorahnRin\CorahnRinBundle\SheetsManagers\PdfManager:
        arguments:
            $sheetsFolder: "%kernel.project_dir%/src/CorahnRin/CorahnRinBundle/Resources/pdf_sources"

    CorahnRin\CorahnRinBundle\GeneratorTools\DomainsCalculator: ~

    CorahnRin\CorahnRinBundle\GeneratorTools\SessionToCharacter:
        public: false
        arguments:
            - '@pierstoval.character_manager.step_action_resolver'
            - '@corahnrin_generator.domains_calculator'
            - '@doctrine.orm.entity_manager'
