services:

    corahnrin_generator.steps.step_01:
        class: CorahnRin\CorahnRinBundle\Action\Step01People
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_02:
        class: CorahnRin\CorahnRinBundle\Action\Step02Job
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_03:
        class: CorahnRin\CorahnRinBundle\Action\Step03Birthplace
        arguments:
            - '%esterenmaps.tile_size%'
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_04:
        class: CorahnRin\CorahnRinBundle\Action\Step04Geo
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_05:
        class: CorahnRin\CorahnRinBundle\Action\Step05SocialClass
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_06:
        class: CorahnRin\CorahnRinBundle\Action\Step06Age
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_07:
        class: CorahnRin\CorahnRinBundle\Action\Step07Setbacks
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_08:
        class: CorahnRin\CorahnRinBundle\Action\Step08Ways
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_09:
        class: CorahnRin\CorahnRinBundle\Action\Step09Traits
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_10:
        class: CorahnRin\CorahnRinBundle\Action\Step10Orientation
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_11:
        class: CorahnRin\CorahnRinBundle\Action\Step11Advantages
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_12:
        class: CorahnRin\CorahnRinBundle\Action\Step12MentalHealth
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_13:
        class: CorahnRin\CorahnRinBundle\Action\Step13PrimaryDomains
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_14:
        class: CorahnRin\CorahnRinBundle\Action\Step14UpgradeDomains
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_15:
        class: CorahnRin\CorahnRinBundle\Action\Step15BonusDomains
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_16:
        class: CorahnRin\CorahnRinBundle\Action\Step16Disciplines
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_17:
        class: CorahnRin\CorahnRinBundle\Action\Step17CombatArts
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_18:
        class: CorahnRin\CorahnRinBundle\Action\Step18Equipment
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_19:
        class: CorahnRin\CorahnRinBundle\Action\Step19Description
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

    corahnrin_generator.steps.step_20:
        class: CorahnRin\CorahnRinBundle\Action\Step20Finish
        calls:
            - ['setDefaultServices', ['@doctrine.orm.entity_manager', '@templating', '@router', '@translator']]

