services:

    corahnrin_generator.steps.step_01:
        class: CorahnRin\CorahnRinBundle\Step\Step01People

    corahnrin_generator.steps.step_02:
        class: CorahnRin\CorahnRinBundle\Step\Step02Job

    corahnrin_generator.steps.step_03:
        class: CorahnRin\CorahnRinBundle\Step\Step03Birthplace
        arguments: [ '%esterenmaps.tile_size%' ]

    corahnrin_generator.steps.step_04:
        class: CorahnRin\CorahnRinBundle\Step\Step04Geo

    corahnrin_generator.steps.step_05:
        class: CorahnRin\CorahnRinBundle\Step\Step05SocialClass

    corahnrin_generator.steps.step_06:
        class: CorahnRin\CorahnRinBundle\Step\Step06Age

    corahnrin_generator.steps.step_07:
        class: CorahnRin\CorahnRinBundle\Step\Step07Setbacks

    corahnrin_generator.steps.step_08:
        class: CorahnRin\CorahnRinBundle\Step\Step08Ways

    corahnrin_generator.steps.step_09:
        class: CorahnRin\CorahnRinBundle\Step\Step09Traits

    corahnrin_generator.steps.step_10:
        class: CorahnRin\CorahnRinBundle\Step\Step10Orientation

    corahnrin_generator.steps.step_11:
        class: CorahnRin\CorahnRinBundle\Step\Step11Advantages

    corahnrin_generator.steps.step_12:
        class: CorahnRin\CorahnRinBundle\Step\Step12MentalDisorder

    corahnrin_generator.steps.step_13:
        class: CorahnRin\CorahnRinBundle\Step\Step13PrimaryDomains

    corahnrin_generator.steps.step_14:
        class: CorahnRin\CorahnRinBundle\Step\Step14UseDomainBonuses
        arguments: [ '@corahnrin_generator.domains_calculator' ]

    corahnrin_generator.steps.step_15:
        class: CorahnRin\CorahnRinBundle\Step\Step15DomainsSpendExp
        arguments: [ '@corahnrin_generator.domains_calculator' ]

    corahnrin_generator.steps.step_16:
        class: CorahnRin\CorahnRinBundle\Step\Step16Disciplines
        arguments: [ '@corahnrin_generator.domains_calculator' ]

    corahnrin_generator.steps.step_17:
        class: CorahnRin\CorahnRinBundle\Step\Step17CombatArts
        arguments: [ '@corahnrin_generator.domains_calculator' ]

    corahnrin_generator.steps.step_18:
        class: CorahnRin\CorahnRinBundle\Step\Step18Equipment

    corahnrin_generator.steps.step_19:
        class: CorahnRin\CorahnRinBundle\Step\Step19Description

    corahnrin_generator.steps.step_20:
        class: CorahnRin\CorahnRinBundle\Step\Step20Finish

