# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    container.dumper.inline_class_loader: true
    container.autowiring.strict_mode: true

    # The version code is always the last version that was put in production
    env(HEROKU_RELEASE_VERSION): 'v50'
    env(HEROKU_RELEASE_CREATED_AT): '2017-07-18T10:53:10Z'

    database_url: '%env(DATABASE_URL)%'
    database_url_legacy: '%env(DATABASE_URL_LEGACY)%'

    version_code: '%env(HEROKU_RELEASE_VERSION)%'
    version_date: '%env(HEROKU_RELEASE_CREATED_AT)%'
    locale: fr
    locales:
        fr: fr
        en: en
    locales_regex: 'fr|en'

    google_tags:
        analytics:   'UA-43812649-5'
        tag_manager: 'GTM-T5PQWF'

    esteren_domains.portal:       'portal.%env(ESTEREN_DOMAIN)%'
    esteren_domains.esterenmaps:    'maps.%env(ESTEREN_DOMAIN)%'
    esteren_domains.corahnrin: 'corahnrin.%env(ESTEREN_DOMAIN)%'
    esteren_domains.games:         'games.%env(ESTEREN_DOMAIN)%'
    esteren_domains.api:             'api.%env(ESTEREN_DOMAIN)%'
    esteren_domains.backoffice:     'back.%env(ESTEREN_DOMAIN)%'

    agate_domains.portal:              'www.%env(AGATE_DOMAIN)%'

    vermine_domains.portal:          'www.%env(VERMINE_DOMAIN)%'

    magick_binaries_path: '%env(IMAGEMAGICK_BINARIES_PATH)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $debug: '%kernel.debug%'
            $sheetsFolder: '%kernel.project_dir%/src/CorahnRin/Resources/pdf_sources'
            $googleTags: '%google_tags%'

    Admin\:
        resource: '../src/Admin/{Controller}'

    Agate\:
        resource: '../src/Agate/{Controller,Mailer}'

    # TODO: remove this when updating CharacterManagerBundle
    Pierstoval\Bundle\CharacterManagerBundle\Resolver\StepActionResolver: '@pierstoval.character_manager.step_action_resolver'

    CorahnRin\:
        resource: '../src/CorahnRin/{Controller,Repository,GeneratorTools,SheetsManagers}'

    Esteren\:
        resource: '../src/Esteren/{Controller,Twig}'
