#
# Root route that redirects "/" to "/%locale%/"
#
root:
    path: /{locale}
    controller: FrameworkBundle:Redirect:urlRedirect
    defaults:
        path: '/%locale%/'
        permanent: true
        locale: '%locale%'
    requirements:
        locale: '^(?:%locales_regex%)$'
    methods: ['GET']

#
# User
#
crowdfunding:
    resource: '../src/User/Controller/Crowdfunding/'
    type: annotation

user_login_check:
    path: /{_locale}/login_check
    methods: ['POST']
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

user_logout:
    path: /{_locale}/logout
    methods: ['GET', 'POST']
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

user_security:
    resource: '../src/User/Controller/'
    type: annotation
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# CorahnRin
#
corahnrin_characters:
    resource: '../src/CorahnRin/Controller/'
    type:     annotation
    host:     '%esteren_domains.corahnrin%'
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

corahnrin_steps:
    resource: '@PierstovalCharacterManagerBundle/Resources/config/routing.xml'
    prefix:   /{_locale}/character
    host:     '%esteren_domains.corahnrin%'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Esteren Maps
# Some controllers use a different domain name, check the @Route annotation on them to be sure.
#
esterenmaps:
    resource: '../src/EsterenMaps/Controller/'
    type:     annotation
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Agate portal
#
agate:
    resource: '../src/Agate/Controller/'
    type: annotation
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Dragons
#
dragons:
    resource: '../src/Dragons/Controller/'
    type: annotation
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Esteren portal
#
esteren_portal:
    resource: '../src/Esteren/Controller/'
    type: annotation
    host: '%esteren_domains.portal%'
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Utils
#
utils:
    resource: '../src/Util/Controller/'
    type: annotation
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }

#
# Admin
#
admin:
    resource: 'routes/easy_admin.yaml'
    prefix: '/{_locale}/'
    defaults: { locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }
