# Please never rename "root".
# It's a hack to help the router take this route in account,
#  so we can benefit from the yaml merge features (check http://yaml.org/type/merge.html)
# The "root" route is overriden by the RootController, so it's safe and correct
root: &defaults
    path: ''
    methods: ['GET']
    defaults: { _locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }
    trailing_slash_on_root: false

metadata: &metadata
    resource: /dev/null
    type: annotation
    prefix: '/{_locale}'
    defaults: { _locale: '%locale%' }
    requirements: { _locale: '^(?:%locales_regex%)$' }
    trailing_slash_on_root: false

main:
    resource: '../src/Main/Controller/RootController.php'
    type: annotation
    trailing_slash_on_root: false

assets_js:
    <<: *metadata
    resource: '../src/Main/Controller/AssetsController.php'

user_login_check:
    <<: *defaults
    path: /{_locale}/login_check
    methods: ['POST']

user_logout:
    <<: *defaults
    path: /{_locale}/logout
    methods: ['GET', 'POST']

user_security:
    <<: *metadata
    resource: '../src/User/Controller/'

voucher:
    <<: *metadata
    resource: '../src/Voucher/Controller/'
    host: '%agate_domains.portal%'

corahnrin_characters:
    <<: *metadata
    resource: '../src/CorahnRin/Controller/'
    host: '%esteren_domains.corahnrin%'

corahnrin_steps:
    <<: *metadata
    resource: '@PierstovalCharacterManagerBundle/Resources/config/routing.xml'
    type: xml
    prefix: /{_locale}/character
    host: '%esteren_domains.corahnrin%'

esterenmaps:
    <<: *metadata
    resource: '../src/EsterenMaps/Controller/'

esterenmaps_api:
    <<: *metadata
    resource: '../src/EsterenMaps/Controller/Api'
    host: '{host}'
    requirements:
        host: "(%esteren_domains.esterenmaps%|%esteren_domains.corahnrin%|%esteren_domains.backoffice%)"

agate:
    <<: *metadata
    resource: '../src/Agate/Controller/'

dragons:
    <<: *metadata
    resource: '../src/Dragons/Controller/'

esteren_portal:
    <<: *metadata
    resource: '../src/Esteren/Controller/'
    host: '%esteren_domains.portal%'

admin:
    <<: *metadata
    resource: '../src/Admin/Controller/AdminController.php'
    host: '%esteren_domains.backoffice%'
