# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    container.dumper.inline_class_loader: true
    container.autowiring.strict_mode: true

    database_url: '%env(DATABASE_URL)%'
    database_url_legacy: '%env(DATABASE_URL_LEGACY)%'

    version_code: '%env(RELEASE_VERSION)%'
    version_date: '%env(RELEASE_DATE)%'
    locale: fr
    locales:
        fr: fr
        en: en
    locales_regex: 'fr|en'

    google_tags:
        analytics:   'UA-43812649-5'
        tag_manager: 'GTM-T5PQWF'

    esteren_domains.portal:       'portal.%env(ESTEREN_DOMAIN)%'
    esteren_domains.esterenmaps:    'maps.%env(ESTEREN_DOMAIN)%'
    esteren_domains.corahnrin: 'corahnrin.%env(ESTEREN_DOMAIN)%'
    esteren_domains.games:         'games.%env(ESTEREN_DOMAIN)%'
    esteren_domains.api:             'api.%env(ESTEREN_DOMAIN)%'
    esteren_domains.backoffice:     'back.%env(ESTEREN_DOMAIN)%'

    agate_domains.portal:              'www.%env(AGATE_DOMAIN)%'
    agate_domains.stats:             'stats.%env(AGATE_DOMAIN)%'

    dragons_domains.portal:          'www.%env(DRAGONS_DOMAIN)%'

    vermine_domains.portal:          'www.%env(VERMINE_DOMAIN)%'

    esterenmaps.tile_size: 168
    esterenmaps.output_directory: '%kernel.project_dir%/public/maps_tiles/'

    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

    corahnrin_manager_name: 'corahn_rin'

    enable_contact_captcha: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $debug:           '%kernel.debug%'
            $defaultLocale:   '%locale%'
            $googleTags:      '%google_tags%'
            $imageMagickPath: '%env(IMAGEMAGICK_BINARIES_PATH)%'
            $outputDirectory: '%esterenmaps.output_directory%'
            $projectDir:      '%kernel.project_dir%'
            $publicDir:       '%kernel.project_dir%/public/'
            $sheetsFolder:    '%kernel.project_dir%/src/CorahnRin/Resources/pdf_sources'
            $tileSize:        '%esterenmaps.tile_size%'
            $versionCode:     '%version_code%'
            $versionDate:     '%version_date%'
            $oneupFlysystem:  '@oneup_flysystem.assets_fs_filesystem'
            $awsRegion:       '%aws_region%'
            $awsBucket:       '%aws_bucket%'
            $kernelEnvironment: '%kernel.environment%'
            $doctrineResultCache: '@doctrine_cache.providers.result_cache'
            $corahnRinManagerName: '%corahnrin_manager_name%'
            $enableContactCaptcha: '%enable_contact_captcha%'
    _instanceof:
        Main\PublicService:
            public: true
        Main\NotAutoconfigured:
            autoconfigure: false

    Admin\:
        resource: '../src/Admin/{Controller}'

    Agate\:
        resource: '../src/Agate/{Controller,Form,Mailer}'

    CorahnRin\:
        resource: '../src/CorahnRin/{Controller,Repository,GeneratorTools,SheetsManagers,Step}'

    Esteren\:
        resource: '../src/Esteren/{Controller,Twig}'

    EsterenMaps\:
        resource: '../src/EsterenMaps/{Api,Cache,Command,Controller,Repository,Services,Twig}'

    User\:
        resource: '../src/User/{Controller,ConnectApi,Command,Mailer,Form,Repository,Security,Twig,Util}'

    Main\:
        resource: '../src/Main/{Controller,Twig}'

    EsterenMaps\Cache\CacheManager:
        tags: [{ name: doctrine.event_subscriber, connection: default }]
