services:
    # TODO: Remove this if PR https://github.com/symfony/symfony/pull/27437 is merged.
    Symfony\Bundle\FrameworkBundle\Test\TestContainer:
        alias: 'test.service_container'
        public: true
