# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    container.dumper.inline_class_loader: true
    container.autowiring.strict_mode: true

    database_url: '%env(DATABASE_URL)%'
    database_url_legacy: '%env(DATABASE_URL_LEGACY)%'

    version_code: '%env(RELEASE_VERSION)%'
    version_date: '%env(RELEASE_DATE)%'
    locale: fr
    locales:
        fr: fr
        en: en
    locales_regex: 'fr|en'

    google_tags:
        analytics:   'UA-43812649-5'
        tag_manager: 'GTM-T5PQWF'

    esteren_domains.portal:       'portal.%env(ESTEREN_DOMAIN)%'
    esteren_domains.esterenmaps:    'maps.%env(ESTEREN_DOMAIN)%'
    esteren_domains.corahnrin: 'corahnrin.%env(ESTEREN_DOMAIN)%'
    esteren_domains.games:         'games.%env(ESTEREN_DOMAIN)%'
    esteren_domains.api:             'api.%env(ESTEREN_DOMAIN)%'
    esteren_domains.backoffice:     'back.%env(ESTEREN_DOMAIN)%'

    agate_domains.portal:              'www.%env(AGATE_DOMAIN)%'
    agate_domains.stats:             'stats.%env(AGATE_DOMAIN)%'

    dragons_domains.portal:          'www.%env(DRAGONS_DOMAIN)%'

    vermine_domains.portal:          'www.%env(VERMINE_DOMAIN)%'

    esterenmaps.tile_size: 168
    esterenmaps.output_directory: '%kernel.project_dir%/public/maps_tiles/'

    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'

    corahnrin_manager_name: 'corahn_rin'

    enable_contact_captcha: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $debug:           '%kernel.debug%'
            $locales:         '%locales%'
            $googleTags:      '%google_tags%'
            $imageMagickPath: '%env(IMAGEMAGICK_BINARIES_PATH)%'
            $outputDirectory: '%esterenmaps.output_directory%'
            $projectDir:      '%kernel.project_dir%'
            $publicDir:       '%kernel.project_dir%/public/'
            $sheetsFolder:    '%kernel.project_dir%/src/CorahnRin/Resources/pdf_sources'
            $tileSize:        '%esterenmaps.tile_size%'
            $versionCode:     '%version_code%'
            $versionDate:     '%version_date%'
            $oneupFlysystem:  '@oneup_flysystem.assets_fs_filesystem'
            $awsRegion:       '%aws_region%'
            $awsBucket:       '%aws_bucket%'
            $agateDomain:     '%env(AGATE_DOMAIN)%'
            $doctrineResultCache: '@doctrine.result_cache_provider'
            $mapsAcceptableHosts: ['%esteren_domains.esterenmaps%', '%esteren_domains.corahnrin%']
            $corahnRinManagerName: '%corahnrin_manager_name%'
            $enableContactCaptcha: '%enable_contact_captcha%'
    _instanceof:
        Main\DependencyInjection\PublicService:
            public: true
        Voucher\Handler\VoucherHandlerInterface:
            tags: ['subscription.voucher_handler']

    Admin\:
        resource: '../src/Admin/*'

    Agate\:
        resource: '../src/Agate/*'
        exclude: '../src/Agate/{Entity,Exception,Model}'

    CorahnRin\:
        resource: '../src/CorahnRin/*'
        exclude: '../src/CorahnRin/{Data,Entity,Exception,Model,PDF,Resources}'

    Esteren\:
        resource: '../src/Esteren/*'

    EsterenMaps\:
        resource: '../src/EsterenMaps/*'
        exclude: '../src/EsterenMaps/{Constraints,Entity,ImageManagement,Mode}'

    Main\:
        resource: '../src/Main/*'

    Subscription\:
        resource: '../src/Subscription/*'
        exclude: '../src/Subscription/{Constraint,Entity}'

    User\:
        resource: '../src/User/*'
        exclude: '../src/User/{Entity,Model,Security/Exception}'

    Voucher\:
        resource: '../src/Voucher/*'
        exclude: '../src/Voucher/{Entity,Data,Exception}'

    Voucher\Redeem\Redeemer: [!tagged subscription.voucher_handler]

    EsterenMaps\Cache\CacheManager:
        tags: [{ name: doctrine.event_subscriber, connection: default }]

    # This class must not be autoconfigured in the Container,
    # because it is used only by Forms, not the global EventDispatcher.
    Agate\Form\EventListener\CaptchaFormSubscriber:
        autoconfigure: false
