services:

    ## TODO: Remove this file when upgrading to SF 4.1

    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface: '@security.encoder_factory'
    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.default_entity_manager'

    Agate\Repository\UserRepository: ~
    Agate\Security\Provider\UsernameOrEmailProvider: ~
    EsterenMaps\Services\DirectionsManager: ~
