services:
    _defaults:
        autowire: true
        autoconfigure: true

    Esteren\PortalBundle\Controller\:
        resource: '../../Controller'
        public: true

    Esteren\PortalBundle\Twig\GoogleTagsExtension:
        arguments:
            - '%google_tags%'
            - '%kernel.debug%'

    Esteren\PortalBundle\Twig\FlashMessageColorsExtension: ~
    Esteren\PortalBundle\Mailer\PortalMailer: ~
