services:
    portal.twig.google_tags:
        class: Esteren\PortalBundle\Twig\GoogleTagsExtension
        arguments:
            - '%google_tags%'
            - '%kernel.debug%'
        tags: [{ name: twig.extension }]

    portal.twig.flash_colors:
        class: Esteren\PortalBundle\Twig\FlashMessageColorsExtension
        tags: [{ name: twig.extension }]

    esteren_mailer:
        class: Esteren\PortalBundle\Mailer\Mailer
        arguments:
            - '@mailer'
            - '@templating.engine.twig'
