
# Use PierstovalCharacterManager to setup CorahnRin's character generator.
# This bundle has to be standalone as much as possible, to only use config and/or override.
# Services are in "src/CorahnRin/CorahnRinBundle/Resources/config/steps.yml"
pierstoval_character_manager:
    character_class: 'CorahnRin\CorahnRinBundle\Entity\Characters'
    steps:

        01_people:
            action: corahnrin_generator.steps.step_01

        02_job:
            action: corahnrin_generator.steps.step_02
            onchange_clear:
                - '13_primary_domains'
                - '14_use_domain_bonuses'
                - '15_domains_spend_exp'
                - '16_disciplines'
                - '17_combat_arts'

        03_birthplace:
            action: corahnrin_generator.steps.step_03

        04_geo:
            action: corahnrin_generator.steps.step_04
            onchange_clear:
                - '14_use_domain_bonuses'

        05_social_class:
            action: corahnrin_generator.steps.step_05
            onchange_clear:
                - '14_use_domain_bonuses'

        06_age:
            action: corahnrin_generator.steps.step_06
            onchange_clear:
                - '07_setbacks'
                - '14_use_domain_bonuses'

        07_setbacks:
            action: corahnrin_generator.steps.step_07
            depends_on:
                - '06_age'

        08_ways:
            action: corahnrin_generator.steps.step_08
            onchange_clear:
                - '09_traits'
                - '10_orientation'
                - '17_combat_arts'

        09_traits:
            action: corahnrin_generator.steps.step_09
            depends_on:
                - '08_ways'

        10_orientation:
            action: corahnrin_generator.steps.step_10
            depends_on:
                - '08_ways'

        11_advantages:
            action: corahnrin_generator.steps.step_11
            onchange_clear:
                - '13_primary_domains'
                - '14_use_domain_bonuses'
                - '15_domains_spend_exp'
                - '16_disciplines'
                - '17_combat_arts'

        12_mental_disorder:
            action: corahnrin_generator.steps.step_12
            depends_on:
                - '08_ways'

        13_primary_domains:
            action: corahnrin_generator.steps.step_13
            depends_on:
                - '02_job'
                - '11_advantages'
            onchange_clear:
                - '14_use_domain_bonuses'
                - '15_domains_spend_exp'
                - '16_disciplines'
                - '17_combat_arts'

        14_use_domain_bonuses:
            action: corahnrin_generator.steps.step_14
            depends_on:
                - '04_geo'
                - '05_social_class'
                - '13_primary_domains'
            onchange_clear:
                - '15_domains_spend_exp'
                - '16_disciplines'

        15_domains_spend_exp:
            action: corahnrin_generator.steps.step_15
            depends_on:
                - '14_use_domain_bonuses'
            onchange_clear:
                - '16_disciplines'

        16_disciplines:
            action: corahnrin_generator.steps.step_16
            depends_on:
                - '15_domains_spend_exp'

        17_combat_arts:
            action: corahnrin_generator.steps.step_17
            depends_on:
                - '15_domains_spend_exp'

        18_equipment:
            action: corahnrin_generator.steps.step_18

        19_description:
            action: corahnrin_generator.steps.step_19

        20_finish:
            action: corahnrin_generator.steps.step_20

services:
    corahnrin_generator.steps.step_01:
        class: CorahnRin\CorahnRinBundle\Step\Step01People

    corahnrin_generator.steps.step_02:
        class: CorahnRin\CorahnRinBundle\Step\Step02Job

    corahnrin_generator.steps.step_03:
        class: CorahnRin\CorahnRinBundle\Step\Step03Birthplace
        arguments: [ '%esterenmaps.tile_size%' ]

    corahnrin_generator.steps.step_04:
        class: CorahnRin\CorahnRinBundle\Step\Step04Geo

    corahnrin_generator.steps.step_05:
        class: CorahnRin\CorahnRinBundle\Step\Step05SocialClass

    corahnrin_generator.steps.step_06:
        class: CorahnRin\CorahnRinBundle\Step\Step06Age

    corahnrin_generator.steps.step_07:
        class: CorahnRin\CorahnRinBundle\Step\Step07Setbacks

    corahnrin_generator.steps.step_08:
        class: CorahnRin\CorahnRinBundle\Step\Step08Ways

    corahnrin_generator.steps.step_09:
        class: CorahnRin\CorahnRinBundle\Step\Step09Traits

    corahnrin_generator.steps.step_10:
        class: CorahnRin\CorahnRinBundle\Step\Step10Orientation

    corahnrin_generator.steps.step_11:
        class: CorahnRin\CorahnRinBundle\Step\Step11Advantages

    corahnrin_generator.steps.step_12:
        class: CorahnRin\CorahnRinBundle\Step\Step12MentalDisorder

    corahnrin_generator.steps.step_13:
        class: CorahnRin\CorahnRinBundle\Step\Step13PrimaryDomains

    corahnrin_generator.steps.step_14:
        class: CorahnRin\CorahnRinBundle\Step\Step14UseDomainBonuses
        arguments: [ '@corahnrin_generator.domains_calculator' ]

    corahnrin_generator.steps.step_15:
        class: CorahnRin\CorahnRinBundle\Step\Step15DomainsSpendExp
        arguments: [ '@corahnrin_generator.domains_calculator' ]

    corahnrin_generator.steps.step_16:
        class: CorahnRin\CorahnRinBundle\Step\Step16Disciplines
        arguments: [ '@corahnrin_generator.domains_calculator' ]

    corahnrin_generator.steps.step_17:
        class: CorahnRin\CorahnRinBundle\Step\Step17CombatArts
        arguments: [ '@corahnrin_generator.domains_calculator' ]

    corahnrin_generator.steps.step_18:
        class: CorahnRin\CorahnRinBundle\Step\Step18Equipment

    corahnrin_generator.steps.step_19:
        class: CorahnRin\CorahnRinBundle\Step\Step19Description

    corahnrin_generator.steps.step_20:
        class: CorahnRin\CorahnRinBundle\Step\Step20Finish
        arguments: [ '@corahnrin_generator.session_to_character' ]
