
# Entities configuration are stored in these files.
imports:
    - { resource: 'admin/' }

easy_admin:
    site_name: Esteren

    list:
        max_results: 50

    design:
        brand_color: 'rgb(88, 88, 216)'

        assets:
            css:
                - 'css/initializer.css'
                - 'css/admin.css'

        form_theme:
            - 'form/easyadmin_form_theme.html.twig'

        menu:
            - { label: 'admin.links.back_to_site', route: 'portal_home' }

            - { label: 'admin.menu.site' }
            - { entity: 'Pages', icon: 'file-text' }

            - { label: 'admin.menu.esterenmaps' }
            - { entity: 'Maps', icon: 'map' }
            - { entity: 'Factions', icon: 'flag' }

            - label: 'admin.menu.esterenmaps_data'
              children:
                  - { entity: 'Markers' }
                  - { entity: 'Routes' }
                  - { entity: 'Zones' }

            - label: 'admin.menu.types'
              children:
                  - { entity: 'MarkersTypes' }
                  - { entity: 'RoutesTypes' }
                  - { entity: 'ZonesTypes' }
                  - { entity: 'TransportTypes' }

# This is to be kept until these entities will be managed in EasyAdmin
parameters:
    override: |
        ####################
        ## Corahn-Rin
        Armors:
            class: CorahnRin\CorahnRinBundle\Entity\Armors
            list:
                fields: [ id, name, protection, price, availability ]
            form:
                fields: [ name, protection, price, availability ]
        Artifacts:
            class: CorahnRin\CorahnRinBundle\Entity\Artifacts
            list:
                fields: [ id, price, consumption, consumptionInterval, tank, resistance ]
            form:
                fields: [ price, consumption, consumptionInterval, tank, resistance ]
        Avantages:
            class: CorahnRin\CorahnRinBundle\Entity\Avantages
            list:
                fields: [ id, name, nameFemale, xp, augmentation, isDesv ]
            form:
                fields: [ name, nameFemale, xp, augmentation, bonusDisc, isDesv ]
        Books:
            class: CorahnRin\CorahnRinBundle\Entity\Books
            list:
                fields: [ id, name, description ]
            form:
                fields: [ name, description ]
        'Combat Arts':
            class: CorahnRin\CorahnRinBundle\Entity\CombatArts
            list:
                fields: [ id, name, ranged, melee, xp ]
            form:
                fields: [ name, ranged, melee, xp ]
        Disciplines:
            class: CorahnRin\CorahnRinBundle\Entity\Disciplines
            list:
                fields: [ id, name, rank, book, domains ]
            form:
                fields: [ name, rank, book, domains ]
        Disorders:
            class: CorahnRin\CorahnRinBundle\Entity\Disorders
            list:
                fields: [ id, name, ways, book ]
            form:
                fields: [ name, ways, book ]
        Jobs:
            class: CorahnRin\CorahnRinBundle\Entity\Jobs
            list:
                fields: [ id, name, domainPrimary, domainsSecondary, book ]
            form:
                fields: [ name, domainPrimary, domainsSecondary, book ]
        Miracles:
            class: CorahnRin\CorahnRinBundle\Entity\Miracles
            list:
                fields: [ id, name, isMajor, book ]
            form:
                fields: [ name, isMajor, book ]
        Ogham:
            class: CorahnRin\CorahnRinBundle\Entity\Ogham
            list:
                fields: [ id, name, oghamType, book ]
            form:
                fields: [ name, oghamType, book ]
        'Ogham types':
            class: CorahnRin\CorahnRinBundle\Entity\OghamTypes
            list:
                fields: [ id, name, description ]
            form:
                fields: [ name, description ]
        Peoples:
            class: CorahnRin\CorahnRinBundle\Entity\Peoples
            list:
                fields: [ id, name, description, book ]
            form:
                fields: [ name, description, book ]
        Setbacks:
            class: CorahnRin\CorahnRinBundle\Entity\Setbacks
            list:
                fields: [ id, name, malus, book ]
            form:
                fields: [ name, malus, book ]
        SocialClasses:
            class: CorahnRin\CorahnRinBundle\Entity\SocialClasses
            list:
                fields: [ id, name, description, domains ]
            form:
                fields: [ name, description, domains ]
        Traits:
            class: CorahnRin\CorahnRinBundle\Entity\Traits
            list:
                fields: [ id, name, nameFemale, isQuality, isMajor, way, book ]
            form:
                fields: [ name, nameFemale, isQuality, isMajor, way, book ]
        Weapons:
            class: CorahnRin\CorahnRinBundle\Entity\Weapons
            list:
                fields: [ id, name, damage, price, availability, melee, range ]
            form:
                fields: [ name, damage, price, availability, melee, range ]
