imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu

# Monolog is overriden because we need to send an e-mail when there is any error.
monolog:
    handlers:

        console:
            type:  console

        main:
            type:         fingers_crossed
            action_level: critical
            handler:      grouped

        grouped:
            type:    group
            members: [streamed, mailed]

        # Get ALL error logs and put them to stderr for heroku
        streamed:
            type:           stream
            path:           'php://stderr'
            level:          info

        # For any "critical", we send an email
        mailed:
            type:           fingers_crossed
            action_level:   critical
            handler:        mail_buffer
            include_stacktraces: true
        mail_buffer:
            type:           buffer
            handler:        mail_sender
            include_stacktraces: true
        mail_sender:
            type:           swift_mailer
            from_email:     no-reply@esteren.org
            to_email:       pierstoval+esterenprod@gmail.com
            subject:        An Error Occurred!
            level:          debug
            include_stacktraces: true
