
services:
    pierstoval.api.origin_checker:
        class: Pierstoval\Bundle\ApiBundle\Services\OriginChecker
        arguments:
            - "%pierstoval_api.allowed_origins%"
            - "%kernel.debug%"

    pierstoval.api.listener:
        class: Pierstoval\Bundle\ApiBundle\Listeners\JsonResponseListener
        arguments:
            - "%kernel.environment%"
        tags:
            - { name: kernel.event_subscriber }
