corahnrin_characters:
    resource: "@CorahnRinBundle/Controller/"
    type:     annotation
    host:     '%esteren_domains.corahnrin%'

corahnrin_steps:
    resource: "@PierstovalCharacterManagerBundle/Resources/config/routing.yml"
    prefix:   /character
    host:     '%esteren_domains.corahnrin%'
