esterenmaps:
    resource: '@EsterenMapsBundle/Controller/'
    type:     annotation

esterenmaps_api:
    resource: '@EsterenMapsBundle/Controller/Api/'
    type:     annotation
    host:     '%esteren_domains.api%'
