
esteren_portal:
    resource: '@EsterenPortalBundle/Controller/'
    type:     annotation
    host:     '%esteren_domains.portal%'

orbitale_cms_category:
    resource: '@OrbitaleCmsBundle/Resources/config/routing/categories.yaml'
    prefix:   /category/

portal_cms:
    resource: '@OrbitaleCmsBundle/Resources/config/routing/pages.yaml'
    prefix:   /
    defaults:
        domainName: '%esteren_domains.portal%'
        slugs: ''
    requirements:
        domainName: '^(?:%esteren_domains.portal%|%esteren_domains.games%|%esteren_domains.corahnrin%)$'
