services:

    esterenmaps.admin.map:
        class: EsterenMaps\AdminBundle\Admin\MapsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "Map" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\Maps
            - ~
            - @stof_doctrine_extensions.uploadable.manager

    esterenmaps.admin.markersTypes:
        class: EsterenMaps\AdminBundle\Admin\MarkersTypesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "MarkersTypes" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\MarkersTypes
            - ~
            - @stof_doctrine_extensions.uploadable.manager

    esterenmaps.admin.routesTypes:
        class: EsterenMaps\AdminBundle\Admin\RoutesTypesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "RoutesTypes" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\RoutesTypes
            - ~

    esterenmaps.admin.zonesTypes:
        class: EsterenMaps\AdminBundle\Admin\ZonesTypesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "ZonesTypes" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\ZonesTypes
            - ~

    esterenmaps.admin.markers:
        class: EsterenMaps\AdminBundle\Admin\MarkersAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "Markers" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\Markers
            - ~

    esterenmaps.admin.routes:
        class: EsterenMaps\AdminBundle\Admin\RoutesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "Routes" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\Routes
            - ~

    esterenmaps.admin.zones:
        class: EsterenMaps\AdminBundle\Admin\ZonesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "Zones" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\Zones
            - ~