services:

    esterenmaps.admin.map:
        class: EsterenMaps\AdminBundle\Admin\MapsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "Map" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\Maps
            - ~
            - @stof_doctrine_extensions.uploadable.manager

    esterenmaps.admin.markersTypes:
        class: EsterenMaps\AdminBundle\Admin\MarkersTypesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "MarkersTypes" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\MarkersTypes
            - ~
            - @stof_doctrine_extensions.uploadable.manager

    esterenmaps.admin.routesTypes:
        class: EsterenMaps\AdminBundle\Admin\RoutesTypesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "EsterenMaps", label: "RoutesTypes" }
        arguments:
            - ~
            - EsterenMaps\MapsBundle\Entity\RoutesTypes
            - ~